"""Add ZTE 3G managedobjects

Revision ID: 287e90f00943
Revises: 667f21d587d3
Create Date: 2018-02-13 01:57:46.671000

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '287e90f00943'
down_revision = '667f21d587d3'
branch_labels = None
depends_on = None


def upgrade():

    managedobjects = sa.sql.table(
        'managedobjects',
        sa.Column('pk', sa.Integer, sa.Sequence('seq_managedobjects_pk', ), primary_key=True, nullable=False),
        sa.Column('name', sa.String(50), nullable=False),
        sa.Column('notes', sa.Text),
        sa.Column('label', sa.String(200)),
        sa.Column('parent_pk', sa.Integer),
        sa.Column('tech_pk', sa.Integer),
        sa.Column('vendor_pk', sa.Integer),
        sa.Column('modified_by', sa.Integer),
        sa.Column('added_by', sa.Integer),
        sa.Column('date_added', sa.TIMESTAMP, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow),
        sa.Column('date_modified', sa.TIMESTAMP, default=datetime.datetime.utcnow)
    )


    op.bulk_insert(managedobjects, [
        {'name': 'vsDataANR', 'parent_pk': 0, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataEUtranRelation', 'parent_pk': 0, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'EUtranRelation', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'ExternalENBFunction', 'parent_pk': 32, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'ExternalRncFunction', 'parent_pk': 32, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'UtranCellFDD', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataAich', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataAmrEvtTPUeInt', 'parent_pk': 1809, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataAppPriMapping', 'parent_pk': 1659, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataAppPriMappingProfile', 'parent_pk': 1775, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataAppSrvType', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataBasPri', 'parent_pk': 1775, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataBasPriMapping', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataBPriAc', 'parent_pk': 1664, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataBPriAcProfile', 'parent_pk': 1775, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataCelInfoFDD', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataCelSel', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataCfnOffset', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataCHspa', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataCMR', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataCnInfo', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataComEdchEvUpTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataComHsdschEvUpTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataCommEdch', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataCompressMode', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataCpuCtrlPri', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDchEvUeTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDchEvUpTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDchPrdUeTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDedEdchEvUpTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDedIBHsdschEvUpTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDedSHsdschEvUpTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDedSrvTb', 'parent_pk': 1683, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDiamondUserGlobalPara', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDiamondUserImsiList', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDiamondUserSrvPc', 'parent_pk': 1801, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDpiAlgParam', 'parent_pk': 1595, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDpiBasPriMapping', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDpiDrbc', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDpiPartnerIp', 'parent_pk': 1691, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDpiPartnerName', 'parent_pk': 1595, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDrbc', 'parent_pk': 1693, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDrbcProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDtxDrx', 'parent_pk': 1695, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDtxDrxProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataEdchRcDch', 'parent_pk': 1697, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataEdchRcDchProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataEdchRcFach', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataEdchtoDchUpTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataEFach', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataEFachPch', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataETTIEdchEvUpTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataExternalENBFunction', 'parent_pk': 1651, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataExternalRncFunction', 'parent_pk': 1653, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataFachEvUpTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataGbrResLimit', 'parent_pk': 1709, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataGbrResLimitProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataGloAc', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataHoEvtTPUeInt', 'parent_pk': 1809, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataHspa', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterEcNoEvMeasforE', 'parent_pk': 1719, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterEcNoEvMeasforG', 'parent_pk': 1719, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterEcNoEvMeasforU', 'parent_pk': 1719, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterEcNoPrdMeas', 'parent_pk': 1717, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterMeasNoSrvSpec', 'parent_pk': 1718, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterMeasProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterMeaSrvSpec', 'parent_pk': 1718, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterRscpEvMeasforG', 'parent_pk': 1719, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterRscpEvMeasforU', 'parent_pk': 1719, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterRscpPrdMeas', 'parent_pk': 1717, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIntraEcNoEvMeas', 'parent_pk': 1729, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIntraEcNoEvMeasForD', 'parent_pk': 1727, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIntraEcNoPrdMeas', 'parent_pk': 1727, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIntraMeasNoSrvSpec', 'parent_pk': 1728, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIntraMeasProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIntraMeasSrvSpec', 'parent_pk': 1728, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIntraRscpEvMeas', 'parent_pk': 1729, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIntraRscpEvMeasForD', 'parent_pk': 1727, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIntraRscpPrdMeas', 'parent_pk': 1727, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIpLicense', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIubTrPath', 'parent_pk': 1745, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIubTrPathCir', 'parent_pk': 1734, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIuCnst', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIucsLink', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIupsLink', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIupsTrPath', 'parent_pk': 1746, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIupsTrPathCir', 'parent_pk': 1739, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIurTrPath', 'parent_pk': 1748, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataIurTrPathCir', 'parent_pk': 1741, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLdCtrl', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLogicalCell', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLogicalIubLink', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLogicalIupsLink', 'parent_pk': 1747, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLogicalIupsLinkGroup', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLogicalIurLink', 'parent_pk': 1767, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLogicalIurQos', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLogicalMgwLink', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLogicalMscLink', 'parent_pk': 1752, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLogicalRnc', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataMgwTrPath', 'parent_pk': 1750, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataMgwTrPathCir', 'parent_pk': 1754, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataMPO', 'parent_pk': 1757, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataMPOProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataMR', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataNbapLink', 'parent_pk': 25, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataNbComMeas', 'parent_pk': 1761, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataNbComMeasProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataNbDedMeas', 'parent_pk': 1763, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataNbDedMeasProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataPchEvUeTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataPicoSonMeasCfg', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataPlBal', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataPlmnAdjFunction', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataPlmnSpecFunction', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataPrach', 'parent_pk': 1655, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataPrdRttUeInt', 'parent_pk': 1809, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataPriSel', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataPwrLimTPUeInt', 'parent_pk': 1809, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataQChat', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataQosFunction', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRachEvtUeTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRachPrdUeTrv', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRatEcNoEvMeasforE', 'parent_pk': 1783, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRatEcNoEvMeasforG', 'parent_pk': 1783, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRatEcNoPrdMeas', 'parent_pk': 1781, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRatMeasNoSrvSpec', 'parent_pk': 1782, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRatMeasSrvSpec', 'parent_pk': 1782, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRatRscpEvMeasforE', 'parent_pk': 1783, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRatRscpEvMeasforG', 'parent_pk': 1783, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRatRscpPrdMeas', 'parent_pk': 1781, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRlEvtRttUeInt', 'parent_pk': 1809, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRncInfo', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRncPool', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRnluCfg', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRrcCategoryBasPriMapping', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRrcCategoryMapping', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRsvdUeGlobalPara', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRsvdUeImsiList', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRsvdUserSrvPc', 'parent_pk': 1801, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataSccpch', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataSchPriMapping', 'parent_pk': 1798, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataSchPriMappingProfile', 'parent_pk': 1775, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataSrvBasedHo', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataSrvDivPc', 'parent_pk': 1802, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataSrvFunction', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataSrvPc', 'parent_pk': 1803, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataSubSrv', 'parent_pk': 1801, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataTbType', 'parent_pk': 1806, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataTbTypeProfile', 'parent_pk': 1775, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataTrvMeasProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataUeCnst', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataUeIntMeasProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataUtranCellFDD', 'parent_pk': 1654, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataUtranRegArea', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'ExternalEUtranCellFDD', 'parent_pk': 1651, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataDedSrvTbProfile', 'parent_pk': 1775, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataEvtRttUeInt', 'parent_pk': 1809, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataInterRscpEvMeasforE', 'parent_pk': 1719, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataLogicalMscLinkGroup', 'parent_pk': 1768, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataPsEvtTPUeInt', 'parent_pk': 1809, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataRatMeasProfile', 'parent_pk': 31, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
        {'name': 'vsDataSrvPcProfile', 'parent_pk': 1801, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0},
    ])


def downgrade():
    op.execute("""DELETE FROM managedobjects WHERE vendor_pk = {0} AND tech_pk = {1}""".format(3, 2))
