"""Add ZTE 3G managedobjects

Revision ID: 287e90f00943
Revises: 667f21d587d3
Create Date: 2018-02-13 01:57:46.671000

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '287e90f00943'
down_revision = '667f21d587d3'
branch_labels = None
depends_on = None


def upgrade():

    managedobjects = sa.sql.table(
        'managedobjects',
        sa.Column('pk', sa.Integer, sa.Sequence('seq_managedobjects_pk', ), primary_key=True, nullable=False),
        sa.Column('name', sa.String(50), nullable=False),
        sa.Column('notes', sa.Text),
        sa.Column('label', sa.String(200)),
        sa.Column('parent_pk', sa.Integer),
        sa.Column('tech_pk', sa.Integer),
        sa.Column('vendor_pk', sa.Integer),
        sa.Column('modified_by', sa.Integer),
        sa.Column('added_by', sa.Integer),
        sa.Column('date_added', sa.TIMESTAMP, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow),
        sa.Column('date_modified', sa.TIMESTAMP, default=datetime.datetime.utcnow)
    )

    op.bulk_insert(managedobjects, [
        {'name': 'vsDataDpiAppSrvProfile', 'parent_pk': 1854, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1800},
        {'name': 'IubLink', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1797},
        {'name': 'vsDataCnInfo', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1799},
        {'name': 'vsDataInterMeaSrvSpec', 'parent_pk': 1894, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1802},
        {'name': 'vsDataIupsTrPath', 'parent_pk': 1926, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1803},
        {'name': 'vsDataNbComMeasProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1804},
        {'name': 'vsDataPchEvUeTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1805},
        {'name': 'EUtranRelation', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1806},
        {'name': 'ManagedElement', 'parent_pk': 1817, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1798},
        {'name': 'bulkCmConfigDataFile', 'parent_pk': 0, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1813},
        {'name': 'configData', 'parent_pk': 0, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1814},
        {'name': 'fileFooter', 'parent_pk': 0, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1815},
        {'name': 'fileHeader', 'parent_pk': 0, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1816},
        {'name': 'ExternalGsmCell', 'parent_pk': 1819, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1809},
        {'name': 'ExternalUtranCellFDD', 'parent_pk': 1810, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1811},
        {'name': 'SubNetwork', 'parent_pk': 1814, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1819},
        {'name': 'ExternalENBFunction', 'parent_pk': 1819, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1807},
        {'name': 'ExternalRncFunction', 'parent_pk': 1819, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1810},
        {'name': 'GsmRelation', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1812},
        {'name': 'meContext', 'parent_pk': 1820, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1817},
        {'name': 'SubNetwork_2', 'parent_pk': 1819, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1820},
        {'name': 'UtranCellFDD', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1821},
        {'name': 'UtranRelation', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1822},
        {'name': 'vsDataAmrEvtTPUeInt', 'parent_pk': 1992, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1824},
        {'name': 'vsDataANR', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1825},
        {'name': 'vsDataAppPriMapping', 'parent_pk': 1827, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1826},
        {'name': 'vsDataAppPriMappingProfile', 'parent_pk': 1954, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1827},
        {'name': 'vsDataAppSrvType', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1828},
        {'name': 'vsDataBasPri', 'parent_pk': 1954, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1829},
        {'name': 'vsDataBasPriMapping', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1830},
        {'name': 'vsDataBPriAc', 'parent_pk': 1832, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1831},
        {'name': 'vsDataBPriAcProfile', 'parent_pk': 1954, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1832},
        {'name': 'vsDataCelInfoFDD', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1833},
        {'name': 'vsDataCelSel', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1834},
        {'name': 'vsDataCfnOffset', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1835},
        {'name': 'vsDataCHspa', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1836},
        {'name': 'vsDataCMR', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1837},
        {'name': 'vsDataComEdchEvUpTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1838},
        {'name': 'vsDataComHsdschEvUpTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1839},
        {'name': 'vsDataCommEdch', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1840},
        {'name': 'vsDataCompressMode', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1841},
        {'name': 'vsDataCpuCtrlPri', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1842},
        {'name': 'vsDataDchEvUeTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1843},
        {'name': 'vsDataDchPrdUeTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1845},
        {'name': 'vsDataDedEdchEvUpTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1846},
        {'name': 'vsDataDedIBHsdschEvUpTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1847},
        {'name': 'vsDataDedSHsdschEvUpTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1848},
        {'name': 'vsDataDedSrvTb', 'parent_pk': 1850, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1849},
        {'name': 'vsDataDedSrvTbProfile', 'parent_pk': 1954, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1850},
        {'name': 'vsDataDiamondUserGlobalPara', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1851},
        {'name': 'vsDataDiamondUserImsiList', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1852},
        {'name': 'vsDataDiamondUserSrvPc', 'parent_pk': 1984, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1853},
        {'name': 'vsDataDpi', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1854},
        {'name': 'vsDataDpiAlgParam', 'parent_pk': 1854, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1855},
        {'name': 'vsDataDpiAppSrv', 'parent_pk': 1854, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1856},
        {'name': 'vsDataDpiAppSrvPri', 'parent_pk': 1800, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1857},
        {'name': 'vsDataDpiBasPriMapping', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1858},
        {'name': 'vsDataDpiDrbc', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1859},
        {'name': 'vsDataDpiPartnerIp', 'parent_pk': 1861, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1860},
        {'name': 'vsDataDpiPartnerName', 'parent_pk': 1854, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1861},
        {'name': 'vsDataDpiProcMap', 'parent_pk': 1854, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1862},
        {'name': 'vsDataDrbc', 'parent_pk': 1864, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1863},
        {'name': 'vsDataDrbcProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1864},
        {'name': 'vsDataDtxDrx', 'parent_pk': 1866, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1865},
        {'name': 'vsDataDtxDrxProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1866},
        {'name': 'vsDataEdchRcDch', 'parent_pk': 1868, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1867},
        {'name': 'vsDataEdchRcDchProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1868},
        {'name': 'vsDataEdchtoDchUpTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1870},
        {'name': 'vsDataEFach', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1871},
        {'name': 'vsDataEFachPch', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1872},
        {'name': 'vsDataETTIEdchEvUpTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1873},
        {'name': 'vsDataEUtranRelation', 'parent_pk': 1806, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1874},
        {'name': 'vsDataEvtRttUeInt', 'parent_pk': 1992, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1875},
        {'name': 'vsDataExternalENBFunction', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1876},
        {'name': 'vsDataExternalEUtranCellFDD', 'parent_pk': 1808, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1877},
        {'name': 'vsDataExternalGsmCell', 'parent_pk': 1809, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1878},
        {'name': 'vsDataExternalRncFunction', 'parent_pk': 1810, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1879},
        {'name': 'vsDataFachEvUpTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1880},
        {'name': 'vsDataFTPInfoCfg', 'parent_pk': 1882, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1881},
        {'name': 'vsDataFullSignalTrace', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1882},
        {'name': 'vsDataGbrResLimit', 'parent_pk': 1884, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1883},
        {'name': 'vsDataGbrResLimitProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1884},
        {'name': 'vsDataGloAc', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1885},
        {'name': 'vsDataGsmRelation', 'parent_pk': 1812, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1886},
        {'name': 'vsDataHoEvtTPUeInt', 'parent_pk': 1992, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1887},
        {'name': 'vsDataHspa', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1888},
        {'name': 'vsDataInterEcNoEvMeasforE', 'parent_pk': 1802, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1889},
        {'name': 'ExternalEUtranCellFDD', 'parent_pk': 1807, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1808},
        {'name': 'vsDataInterEcNoEvMeasforU', 'parent_pk': 1802, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1891},
        {'name': 'vsDataInterEcNoPrdMeas', 'parent_pk': 1893, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1892},
        {'name': 'vsDataInterMeasNoSrvSpec', 'parent_pk': 1894, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1893},
        {'name': 'vsDataInterMeasProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1894},
        {'name': 'vsDataInterRscpEvMeasforE', 'parent_pk': 1802, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1895},
        {'name': 'vsDataInterRscpEvMeasforG', 'parent_pk': 1802, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1896},
        {'name': 'vsDataInterRscpEvMeasforU', 'parent_pk': 1802, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1897},
        {'name': 'vsDataInterRscpPrdMeas', 'parent_pk': 1893, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1898},
        {'name': 'vsDataIntraEcNoEvMeas', 'parent_pk': 1904, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1899},
        {'name': 'vsDataIntraEcNoEvMeasForD', 'parent_pk': 1902, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1900},
        {'name': 'vsDataIntraEcNoPrdMeas', 'parent_pk': 1902, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1901},
        {'name': 'vsDataIntraMeasNoSrvSpec', 'parent_pk': 1903, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1902},
        {'name': 'vsDataIntraMeasProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1903},
        {'name': 'vsDataIntraMeasSrvSpec', 'parent_pk': 1903, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1904},
        {'name': 'vsDataIntraRscpEvMeas', 'parent_pk': 1904, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1905},
        {'name': 'vsDataIntraRscpEvMeasForD', 'parent_pk': 1902, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1906},
        {'name': 'vsDataIntraRscpPrdMeas', 'parent_pk': 1902, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1907},
        {'name': 'vsDataIpbm', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1908},
        {'name': 'vsDataIpLicense', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1909},
        {'name': 'vsDataIpSlaExTask', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1910},
        {'name': 'vsDataIubLink', 'parent_pk': 1797, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1911},
        {'name': 'vsDataIubTrPath', 'parent_pk': 1925, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1912},
        {'name': 'vsDataIuCnst', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1914},
        {'name': 'vsDataIucsLink', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1915},
        {'name': 'vsDataIupsLink', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1916},
        {'name': 'vsDataIupsTrPathCir', 'parent_pk': 1803, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1917},
        {'name': 'vsDataIurgLink', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1918},
        {'name': 'vsDataIurLink', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1919},
        {'name': 'vsDataIurTrPath', 'parent_pk': 1929, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1920},
        {'name': 'vsDataIurTrPathCir', 'parent_pk': 1920, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1921},
        {'name': 'vsDataLdCtrl', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1922},
        {'name': 'vsDataLocationArea', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1923},
        {'name': 'vsDataLogicalCell', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1924},
        {'name': 'vsDataLogicalIubLink', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1925},
        {'name': 'vsDataLogicalIupsLink', 'parent_pk': 1927, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1926},
        {'name': 'vsDataLogicalIupsLinkGroup', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1927},
        {'name': 'vsDataLogicalIurgLink', 'parent_pk': 1946, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1928},
        {'name': 'vsDataLogicalIurLink', 'parent_pk': 1946, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1929},
        {'name': 'vsDataLogicalIurQos', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1930},
        {'name': 'vsDataLogicalMgwLink', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1931},
        {'name': 'vsDataLogicalMscLink', 'parent_pk': 1933, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1932},
        {'name': 'vsDataLogicalMscLinkGroup', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1933},
        {'name': 'vsDataLogicalRnc', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1934},
        {'name': 'vsDataMgwTrPath', 'parent_pk': 1931, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1935},
        {'name': 'vsDataMPO', 'parent_pk': 1938, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1937},
        {'name': 'vsDataMPOProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1938},
        {'name': 'vsDataMR', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1939},
        {'name': 'vsDataNbapLink', 'parent_pk': 1797, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1940},
        {'name': 'vsDataNbComMeas', 'parent_pk': 1804, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1941},
        {'name': 'vsDataNbDedMeas', 'parent_pk': 1943, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1942},
        {'name': 'vsDataNbDedMeasProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1943},
        {'name': 'vsDataPicoSonMeasCfg', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1944},
        {'name': 'vsDataPlBal', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1945},
        {'name': 'vsDataPlmnAdjFunction', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1946},
        {'name': 'vsDataPlmnSpecFunction', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1947},
        {'name': 'vsDataPrach', 'parent_pk': 1823, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1948},
        {'name': 'vsDataPrdRttUeInt', 'parent_pk': 1992, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1949},
        {'name': 'vsDataPriSel', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1950},
        {'name': 'vsDataPsEvtTPUeInt', 'parent_pk': 1992, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1951},
        {'name': 'vsDataPwrLimTPUeInt', 'parent_pk': 1992, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1952},
        {'name': 'vsDataQChat', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1953},
        {'name': 'vsDataQosFunction', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1954},
        {'name': 'vsDataRachEvtUeTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1955},
        {'name': 'vsDataRachPrdUeTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1956},
        {'name': 'vsDataRatEcNoEvMeasforE', 'parent_pk': 1962, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1957},
        {'name': 'vsDataRatEcNoEvMeasforG', 'parent_pk': 1962, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1958},
        {'name': 'vsDataRatEcNoPrdMeas', 'parent_pk': 1960, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1959},
        {'name': 'vsDataRatMeasNoSrvSpec', 'parent_pk': 1961, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1960},
        {'name': 'vsDataRatMeasSrvSpec', 'parent_pk': 1961, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1962},
        {'name': 'vsDataRatRscpEvMeasforE', 'parent_pk': 1962, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1963},
        {'name': 'vsDataRatRscpEvMeasforG', 'parent_pk': 1962, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1964},
        {'name': 'vsDataRatRscpPrdMeas', 'parent_pk': 1960, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1965},
        {'name': 'vsDataRlEvtRttUeInt', 'parent_pk': 1992, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1966},
        {'name': 'vsDataRncFunction', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1967},
        {'name': 'vsDataRncInfo', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1968},
        {'name': 'vsDataRncPool', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1969},
        {'name': 'vsDataRnluCfg', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1970},
        {'name': 'vsDataRoutingArea', 'parent_pk': 1923, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1971},
        {'name': 'vsDataRrcCategoryMapping', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1973},
        {'name': 'vsDataRsvdUeGlobalPara', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1974},
        {'name': 'vsDataRsvdUeImsiList', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1975},
        {'name': 'vsDataRsvdUserSrvPc', 'parent_pk': 1984, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1976},
        {'name': 'vsDataSccpch', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1977},
        {'name': 'vsDataSchPriMappingProfile', 'parent_pk': 1954, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1979},
        {'name': 'vsDataServiceArea', 'parent_pk': 1923, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1980},
        {'name': 'vsDataSignalTraceCfg', 'parent_pk': 1882, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1981},
        {'name': 'vsDataSrvBasedHo', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1982},
        {'name': 'vsDataSrvDivPc', 'parent_pk': 1985, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1983},
        {'name': 'vsDataSrvFunction', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1984},
        {'name': 'vsDataSrvPc', 'parent_pk': 1986, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1985},
        {'name': 'vsDataSrvPcProfile', 'parent_pk': 1984, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1986},
        {'name': 'vsDataSubSrv', 'parent_pk': 1984, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1987},
        {'name': 'vsDataTbType', 'parent_pk': 1989, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1988},
        {'name': 'vsDataTbTypeProfile', 'parent_pk': 1954, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1989},
        {'name': 'vsDataTrvMeasProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1990},
        {'name': 'vsDataUeCnst', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1991},
        {'name': 'vsDataUeIntMeasProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1992},
        {'name': 'vsDataUtranCellFDD', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1993},
        {'name': 'vsDataUtranRegArea', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1994},
        {'name': 'vsDataUtranRelation', 'parent_pk': 1822, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1995},
        {'name': 'vsDataAich', 'parent_pk': 1821, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1823},
        {'name': 'vsDataDchEvUpTrv', 'parent_pk': 1990, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1844},
        {'name': 'vsDataEdchRcFach', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1869},
        {'name': 'vsDataInterEcNoEvMeasforG', 'parent_pk': 1802, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1890},
        {'name': 'vsDataIubTrPathCir', 'parent_pk': 1912, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1913},
        {'name': 'vsDataMgwTrPathCir', 'parent_pk': 1935, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1936},
        {'name': 'vsDataRatMeasProfile', 'parent_pk': 1818, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1961},
        {'name': 'vsDataRrcCategoryBasPriMapping', 'parent_pk': 1947, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1972},
        {'name': 'vsDataSchPriMapping', 'parent_pk': 1979, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1978},
        {'name': 'RncFunction', 'parent_pk': 1798, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 1818},
        {'name': 'vsDataExternalUtranCellFDD', 'parent_pk': 1811, 'vendor_pk': 3, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 1801},
    ])


def downgrade():
    op.execute("""DELETE FROM managedobjects WHERE vendor_pk = {0} AND tech_pk = {1}""".format(3, 2))
