"""Add Ericsson 3G4G managedobjects

Revision ID: 3fa514f1b7a9
Revises: 31473ada8975
Create Date: 2018-02-13 01:34:32.464000

"""
from alembic import op
import sqlalchemy as sa
import datetime

# revision identifiers, used by Alembic.
revision = '3fa514f1b7a9'
down_revision = '31473ada8975'
branch_labels = None
depends_on = None


def upgrade():

    managedobjects = sa.sql.table(
        'managedobjects',
        sa.Column('pk', sa.Integer, sa.Sequence('seq_managedobjects_pk', ), primary_key=True, nullable=False),
        sa.Column('name', sa.String(50), nullable=False),
        sa.Column('notes', sa.Text),
        sa.Column('label', sa.String(200)),
        sa.Column('parent_pk', sa.Integer),
        sa.Column('tech_pk', sa.Integer),
        sa.Column('vendor_pk', sa.Integer),
        sa.Column('modified_by', sa.Integer),
        sa.Column('added_by', sa.Integer),
        sa.Column('date_added', sa.TIMESTAMP, default=datetime.datetime.utcnow, onupdate=datetime.datetime.utcnow),
        sa.Column('date_modified', sa.TIMESTAMP, default=datetime.datetime.utcnow)
    )

    op.bulk_insert(managedobjects, [
        {'name': 'fileFooter', 'parent_pk': 0, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0, 'pk': 17},
        {'name': 'fileHeader', 'parent_pk': 0, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0, 'pk': 18},
        {'name': 'vsDataAal0TpVccTp', 'parent_pk': 586, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 34},
        {'name': 'vsDataAal2Ap', 'parent_pk': 43, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 35},
        {'name': 'vsDataAal2PathDistributionUnit', 'parent_pk': 37, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 36},
        {'name': 'vsDataAal2PathVccTp', 'parent_pk': 586, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 37},
        {'name': 'vsDataAdmissionControl', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 45},
        {'name': 'vsDataAal2RoutingCase', 'parent_pk': 586, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 40},
        {'name': 'vsDataAirIfLoadProfile', 'parent_pk': 160, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 50},
        {'name': 'vsDataAnrFunctionCdma20001xRtt', 'parent_pk': 58, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 56},
        {'name': 'vsDataAdvCellSup', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 46},
        {'name': 'vsDataAntennaNearUnit', 'parent_pk': 68, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 62},
        {'name': 'ExternalGsmCell', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 20},
        {'name': 'GsmRelation', 'parent_pk': 32, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 21},
        {'name': 'IRPAgent', 'parent_pk': 25, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0, 'pk': 22},
        {'name': 'bulkCmConfigDataFile', 'parent_pk': 0, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 15},
        {'name': 'IubLink', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0, 'pk': 23},
        {'name': 'ManagedElement', 'parent_pk': 26, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 24},
        {'name': 'ManagementNode', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 25},
        {'name': 'NodeBFunction', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 27},
        {'name': 'NotificationIRP', 'parent_pk': 22, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 28},
        {'name': 'UtranRelation', 'parent_pk': 32, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 33},
        {'name': 'vsDataAal2QosProfile', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 39},
        {'name': 'vsDataAal2Sp', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 41},
        {'name': 'vsDataAal5TpVccTp', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 42},
        {'name': 'vsDataAccessControlList', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 43},
        {'name': 'vsDataSchedulerSp', 'parent_pk': 488, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 471},
        {'name': 'vsDataAiDevice', 'parent_pk': 392, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 47},
        {'name': 'vsDataAiDeviceSet', 'parent_pk': 392, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 48},
        {'name': 'vsDataAisgv2FwDownload', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 51},
        {'name': 'vsDataAlarmPort', 'parent_pk': 614, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 52},
        {'name': 'vsDataAmoFunction', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 53},
        {'name': 'vsDataAnr', 'parent_pk': 274, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 54},
        {'name': 'vsDataAnrFunction', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 55},
        {'name': 'vsDataAnrFunctionEUtran', 'parent_pk': 55, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 57},
        {'name': 'vsDataAnrFunctionGeran', 'parent_pk': 55, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 58},
        {'name': 'vsDataAnrFunctionUtran', 'parent_pk': 55, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 59},
        {'name': 'vsDataAntennaBranch', 'parent_pk': 479, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 61},
        {'name': 'vsDataAntennaSubunit', 'parent_pk': 64, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 63},
        {'name': 'vsDataAntennaUnit', 'parent_pk': 65, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 64},
        {'name': 'vsDataAntennaUnitGroup', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 65},
        {'name': 'vsDataAntFeederCable', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 66},
        {'name': 'vsDataAreas', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 67},
        {'name': 'vsDataArpMap', 'parent_pk': 68, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 68},
        {'name': 'vsDataArpQosClassProfile', 'parent_pk': 381, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 69},
        {'name': 'vsDataAtmConfService', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 70},
        {'name': 'vsDataAuPort', 'parent_pk': 63, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 71},
        {'name': 'vsDataAuthenticationOrder', 'parent_pk': 581, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 72},
        {'name': 'vsDataAuthorizationOrder', 'parent_pk': 581, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 73},
        {'name': 'vsDataAutoCellCapEstFunction', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 74},
        {'name': 'vsDataAutonomousMode', 'parent_pk': 276, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 75},
        {'name': 'vsDataAutoProvisioning', 'parent_pk': 327, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 76},
        {'name': 'vsDataAuxPlugInUnit', 'parent_pk': 393, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 77},
        {'name': 'vsDataBatteryBackup', 'parent_pk': 158, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 78},
        {'name': 'vsDataBbProcessingResource', 'parent_pk': 79, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 79},
        {'name': 'vsDataBestNeighborSI', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 80},
        {'name': 'vsDataBfdProfile', 'parent_pk': 254, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 81},
        {'name': 'vsDataBoundaryOrdinaryClock', 'parent_pk': 370, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 82},
        {'name': 'vsDataBridge', 'parent_pk': 83, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 83},
        {'name': 'vsDataBrM', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 84},
        {'name': 'SubNetwork_2', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 31},
        {'name': 'MeContext', 'parent_pk': 31, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0, 'pk': 26},
        {'name': 'UtranCell', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0, 'pk': 32},
        {'name': 'BulkCmIRP', 'parent_pk': 22, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0, 'pk': 19},
        {'name': 'vsDataSRVCCtoUTRAN', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 501},
        {'name': 'configData', 'parent_pk': 0, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0, 'pk': 16},
        {'name': 'vsDataBrmBackupLabelStore', 'parent_pk': 88, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 87},
        {'name': 'vsDataBrmBackupManager', 'parent_pk': 84, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 88},
        {'name': 'vsDataBrmBackupScheduler', 'parent_pk': 88, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 89},
        {'name': 'vsDataBrmFailsafeBackup', 'parent_pk': 88, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 91},
        {'name': 'vsDataBrmPeriodicEvent', 'parent_pk': 89, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 92},
        {'name': 'vsDataBrmRollbackAtRestore', 'parent_pk': 84, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 93},
        {'name': 'vsDataBrmSingleEvent', 'parent_pk': 89, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 94},
        {'name': 'vsDataCabinet', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 95},
        {'name': 'vsDataCapacityChannelBandwidth', 'parent_pk': 99, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 96},
        {'name': 'vsDataCapacityFeatureLicense', 'parent_pk': 274, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 97},
        {'name': 'vsDataCapacityKey', 'parent_pk': 276, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 98},
        {'name': 'vsDataCapacityLicenses', 'parent_pk': 274, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 99},
        {'name': 'vsDataCapacityState', 'parent_pk': 276, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 100},
        {'name': 'vsDataCarrier', 'parent_pk': 478, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 101},
        {'name': 'vsDataCaxFanUnit', 'parent_pk': 505, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 103},
        {'name': 'vsDataCbu', 'parent_pk': 354, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 104},
        {'name': 'vsDataCchFrameSynch', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 105},
        {'name': 'vsDataCdma2000SessionContinuity', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 106},
        {'name': 'vsDataCellResources', 'parent_pk': 321, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 107},
        {'name': 'vsDataCellSleepFunction', 'parent_pk': 172, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 108},
        {'name': 'vsDataCellSleepNodeFunction', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 109},
        {'name': 'vsDataCertM', 'parent_pk': 477, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 110},
        {'name': 'vsDataCertMCapabilities', 'parent_pk': 110, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 111},
        {'name': 'vsDataChannelSwitching', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 112},
        {'name': 'vsDataClimate', 'parent_pk': 158, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 113},
        {'name': 'vsDataCliSsh', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 114},
        {'name': 'vsDataCliTls', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 115},
        {'name': 'vsDataCnOperator', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 116},
        {'name': 'vsDataCombinedCell', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 117},
        {'name': 'vsDataCommonChannelResourcesDl', 'parent_pk': 321, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 118},
        {'name': 'vsDataCommonChannelResourcesUl', 'parent_pk': 323, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 119},
        {'name': 'vsDataCommunicationContexts', 'parent_pk': 27, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 120},
        {'name': 'vsDataConfigurationVersion', 'parent_pk': 634, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 121},
        {'name': 'vsDataCoverageRelation', 'parent_pk': 32, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 122},
        {'name': 'vsDataCpriLinkSupervision', 'parent_pk': 327, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 123},
        {'name': 'vsDataCsfbForLimitedDualRadioUE', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 124},
        {'name': 'vsDataCsfbToGeranUtran', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 125},
        {'name': 'vsDataDataCollectionGeneration', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 126},
        {'name': 'vsDataDataRadioBearer', 'parent_pk': 383, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 127},
        {'name': 'vsDataDateAndTime', 'parent_pk': 529, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 128},
        {'name': 'vsDataDBSAndSabe', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 129},
        {'name': 'vsDataDchFrameSynch', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 130},
        {'name': 'vsDataDeviceGroup', 'parent_pk': 393, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 131},
        {'name': 'vsDataDhcp', 'parent_pk': 251, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 132},
        {'name': 'vsDataDlFss', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 133},
        {'name': 'vsDataDlPrbCapacity', 'parent_pk': 99, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 134},
        {'name': 'vsDataDnsClient', 'parent_pk': 135, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 135},
        {'name': 'vsDataDrx', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 137},
        {'name': 'vsDataDrxProfile', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 138},
        {'name': 'vsDataDst', 'parent_pk': 139, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 139},
        {'name': 'vsDataDualAntDlPerfPkg', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 140},
        {'name': 'vsDataDualLayBeamfPerfPkg', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 141},
        {'name': 'vsDataDynamicGBRAdmCtrl', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 142},
        {'name': 'vsDataDynamicQoSModification', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 143},
        {'name': 'vsDataE1PhysPathTerm', 'parent_pk': 179, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 144},
        {'name': 'vsDataEcBus', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 145},
        {'name': 'vsDataEcPort', 'parent_pk': 614, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 146},
        {'name': 'vsDataEcsCsfb', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 147},
        {'name': 'vsDataEDchResources', 'parent_pk': 323, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 148},
        {'name': 'vsDataEmergencyUnlock', 'parent_pk': 276, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 149},
        {'name': 'vsDataEnergyMeter', 'parent_pk': 230, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 150},
        {'name': 'vsDataEnhCellIdInTraces', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 151},
        {'name': 'vsDataENodeBFunction', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 152},
        {'name': 'vsDataEnrollmentAuthority', 'parent_pk': 110, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 153},
        {'name': 'vsDataEnrollmentServer', 'parent_pk': 155, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 154},
        {'name': 'vsDataEnrollmentServerGroup', 'parent_pk': 110, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 155},
        {'name': 'vsDataEquipment', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 156},
        {'name': 'vsDataEquipmentDiscovery', 'parent_pk': 327, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 157},
        {'name': 'vsDataEquipmentSupportFunction', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 158},
        {'name': 'vsDataEricssonFilter', 'parent_pk': 272, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 159},
        {'name': 'vsDataEthernetInterface', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 161},
        {'name': 'vsDataEthernetLink', 'parent_pk': 240, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 162},
        {'name': 'vsDataEthernetPort', 'parent_pk': 494, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 163},
        {'name': 'vsDataEthernetSwitch', 'parent_pk': 180, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 164},
        {'name': 'vsDataSid', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 490},
        {'name': 'vsDataTermPointToSGW', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 528},
        {'name': 'vsDataEthernetSwitchModule', 'parent_pk': 354, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 167},
        {'name': 'vsDataEthernetSwitchModulePort', 'parent_pk': 167, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 168},
        {'name': 'vsDataGnssInfo', 'parent_pk': 564, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 211},
        {'name': 'vsDataGpsOutSyncLink', 'parent_pk': 565, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 213},
        {'name': 'vsDataGpsSyncRef', 'parent_pk': 565, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 214},
        {'name': 'vsDataHost', 'parent_pk': 585, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 222},
        {'name': 'vsDataHoWhiteList', 'parent_pk': 535, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 223},
        {'name': 'vsDataImaGroup', 'parent_pk': 586, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 231},
        {'name': 'vsDataImaLink', 'parent_pk': 243, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 232},
        {'name': 'vsDataEthernetSwitchPort', 'parent_pk': 164, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 169},
        {'name': 'vsDataEtws', 'parent_pk': 172, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 170},
        {'name': 'vsDataEul', 'parent_pk': 224, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 171},
        {'name': 'vsDataEUtranCellFDD', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 172},
        {'name': 'vsDataEUtranCellRelation', 'parent_pk': 175, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 173},
        {'name': 'vsDataEUtraNetwork', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 174},
        {'name': 'vsDataEUtranFreqRelation', 'parent_pk': 172, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 175},
        {'name': 'vsDataEUtranFrequency', 'parent_pk': 202, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 176},
        {'name': 'vsDataEventCapabilities', 'parent_pk': 178, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 177},
        {'name': 'vsDataEventProducer', 'parent_pk': 356, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 178},
        {'name': 'vsDataExchangeTerminal', 'parent_pk': 179, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 179},
        {'name': 'vsDataExchangeTerminalIp', 'parent_pk': 180, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 180},
        {'name': 'vsDataExternalEUtranCellFDD', 'parent_pk': 181, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 182},
        {'name': 'vsDataExternalEutranFrequency', 'parent_pk': 202, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 183},
        {'name': 'vsDataExternalEUtranPlmn', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 184},
        {'name': 'vsDataExternalGsmCell', 'parent_pk': 20, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 185},
        {'name': 'vsDataExternalGsmFreq', 'parent_pk': 202, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 186},
        {'name': 'vsDataExternalGsmFreqGroup', 'parent_pk': 202, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 187},
        {'name': 'vsDataExternalGsmPlmn', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 188},
        {'name': 'vsDataExternalNode', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 189},
        {'name': 'vsDataExternalUtranCell', 'parent_pk': 605, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 190},
        {'name': 'vsDataExternalUtranFreq', 'parent_pk': 202, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 191},
        {'name': 'vsDataExternalUtranPlmn', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 192},
        {'name': 'vsDataFach', 'parent_pk': 32, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 193},
        {'name': 'vsDataFanGroup', 'parent_pk': 95, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 194},
        {'name': 'vsDataFeatureState', 'parent_pk': 276, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 195},
        {'name': 'vsDataFileTPM', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 196},
        {'name': 'vsDataFilter', 'parent_pk': 272, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 197},
        {'name': 'vsDataFm', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 198},
        {'name': 'vsDataFmAlarmModel', 'parent_pk': 198, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 199},
        {'name': 'vsDataFmAlarmType', 'parent_pk': 199, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 200},
        {'name': 'vsDataFmSubscription', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 201},
        {'name': 'vsDataFreqManagement', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 202},
        {'name': 'vsDataFrequencySyncIO', 'parent_pk': 518, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 203},
        {'name': 'vsDataFtpTls', 'parent_pk': 196, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 204},
        {'name': 'vsDataFtpTlsServer', 'parent_pk': 204, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 205},
        {'name': 'vsDataGeneralProcessorUnit', 'parent_pk': 206, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 206},
        {'name': 'vsDataGeranCellRelation', 'parent_pk': 209, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 207},
        {'name': 'vsDataGeraNetwork', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 208},
        {'name': 'vsDataGigaBitEthernet', 'parent_pk': 210, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 210},
        {'name': 'vsDataGpeh', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 212},
        {'name': 'vsDataGracePeriod', 'parent_pk': 100, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 215},
        {'name': 'vsDataGsmRelation', 'parent_pk': 21, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 216},
        {'name': 'vsDataGsmSessionContinuity', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 217},
        {'name': 'vsDataGtpPath', 'parent_pk': 528, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 218},
        {'name': 'vsDataHandover', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 219},
        {'name': 'vsDataHighSpeedUE', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 220},
        {'name': 'vsDataHoOscCtrlUE', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 221},
        {'name': 'vsDataHsdsch', 'parent_pk': 32, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 224},
        {'name': 'vsDataHsDschResources', 'parent_pk': 321, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 225},
        {'name': 'vsDataHttpM', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 226},
        {'name': 'vsDataHttps', 'parent_pk': 226, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 227},
        {'name': 'vsDataHwInventory', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 228},
        {'name': 'vsDataHwItem', 'parent_pk': 228, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 229},
        {'name': 'vsDataHwUnit', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 230},
        {'name': 'vsDataIntegrationUnlock', 'parent_pk': 276, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 233},
        {'name': 'vsDataInterfaceIPv4', 'parent_pk': 254, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 234},
        {'name': 'vsDataInterFrequencyLoadBalancing', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 235},
        {'name': 'vsDataInterFrequencyLTEHandover', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 236},
        {'name': 'vsDataInterFrequencySessionContinuity', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2,
         'modified_by': 0, 'added_by': 0, 'pk': 237},
        {'name': 'vsDataInternalEthernetPort', 'parent_pk': 180, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 238},
        {'name': 'vsDataIntraLTEHODataFwd', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 239},
        {'name': 'vsDataIp', 'parent_pk': 251, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 240},
        {'name': 'vsDataIpAccessHostEt', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 241},
        {'name': 'vsDataIpAccessHostGpb', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 242},
        {'name': 'vsDataIpAccessHostPool', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 243},
        {'name': 'vsDataIpAccessSctp', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 245},
        {'name': 'vsDataTrustCategory', 'parent_pk': 110, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 555},
        {'name': 'vsDataIpHostLink', 'parent_pk': 240, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 248},
        {'name': 'vsDataMtp3bSlItu', 'parent_pk': 324, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 306},
        {'name': 'vsDataMtp3bSls', 'parent_pk': 325, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 307},
        {'name': 'vsDataNniSaalTp', 'parent_pk': 586, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 319},
        {'name': 'vsDataNodeFunction', 'parent_pk': 26, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 325},
        {'name': 'vsDataIpInterface', 'parent_pk': 351, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 249},
        {'name': 'vsDataIpLicensing', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 250},
        {'name': 'vsDataIpOam', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 251},
        {'name': 'vsDataIppm', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 252},
        {'name': 'vsDataIpRoute', 'parent_pk': 460, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 253},
        {'name': 'vsDataIpRouter', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 254},
        {'name': 'vsDataIpRouteSys', 'parent_pk': 460, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 255},
        {'name': 'vsDataIpRoutingTable', 'parent_pk': 240, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 256},
        {'name': 'vsDataIpSec', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 257},
        {'name': 'vsDataIpSyncRef', 'parent_pk': 241, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 258},
        {'name': 'vsDataIpSystem', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 259},
        {'name': 'vsDataIpv4DestNetwork', 'parent_pk': 261, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 260},
        {'name': 'vsDataIpv4StaticRouteTable', 'parent_pk': 254, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 261},
        {'name': 'vsDataIPv6RoutingTable', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 262},
        {'name': 'vsDataIrc', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 263},
        {'name': 'vsDataIub', 'parent_pk': 27, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 264},
        {'name': 'vsDataIubDataStreams', 'parent_pk': 264, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 265},
        {'name': 'vsDataIubLink', 'parent_pk': 23, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 266},
        {'name': 'vsDataIuLink', 'parent_pk': 116, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 267},
        {'name': 'vsDataIurLink', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 268},
        {'name': 'vsDataKeyFileManagement', 'parent_pk': 276, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 270},
        {'name': 'vsDataLag', 'parent_pk': 167, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 271},
        {'name': 'vsDataLdap', 'parent_pk': 273, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 272},
        {'name': 'vsDataLdapAuthenticationMethod', 'parent_pk': 581, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 273},
        {'name': 'vsDataLicensing', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 274},
        {'name': 'vsDataLinkTransmissionProfile', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 275},
        {'name': 'vsDataLm', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 276},
        {'name': 'vsDataLoadBalancingFunction', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 277},
        {'name': 'vsDataLoadControl', 'parent_pk': 206, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 278},
        {'name': 'vsDataLocationArea', 'parent_pk': 352, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 279},
        {'name': 'vsDataLog', 'parent_pk': 282, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 280},
        {'name': 'vsDataLogicalChannelGroup', 'parent_pk': 374, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 281},
        {'name': 'vsDataLogM', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 282},
        {'name': 'vsDataLppaEcid', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 283},
        {'name': 'vsDataLsmEcs', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 284},
        {'name': 'vsDataM3uAssociation', 'parent_pk': 308, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 285},
        {'name': 'vsDataMACConfiguration', 'parent_pk': 383, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 286},
        {'name': 'vsDataMaintenanceUser', 'parent_pk': 580, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 287},
        {'name': 'vsDataMaintenanceUserSecurity', 'parent_pk': 580, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 288},
        {'name': 'vsDataManagedElement', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 289},
        {'name': 'vsDataManagedElementData', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 290},
        {'name': 'vsDataMaximumCellRange', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 291},
        {'name': 'vsDataMbmsM3Based', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 292},
        {'name': 'vsDataMbmsServiceArea', 'parent_pk': 352, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 293},
        {'name': 'vsDataMdtConfiguration', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 294},
        {'name': 'vsDataMeContext', 'parent_pk': 26, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 296},
        {'name': 'vsDataMediumAccessUnit', 'parent_pk': 297, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 297},
        {'name': 'vsDataMibManager', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 298},
        {'name': 'vsDataMimoSleepFunction', 'parent_pk': 172, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 299},
        {'name': 'vsDataMixedMode', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 300},
        {'name': 'vsDataMobCtrlAtPoorCov', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 301},
        {'name': 'vsDataMocnCellProfile', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 302},
        {'name': 'vsDataMpClusterHandling', 'parent_pk': 327, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 303},
        {'name': 'vsDataMpProcessingResource', 'parent_pk': 304, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 304},
        {'name': 'vsDataMtp3bAp', 'parent_pk': 308, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 305},
        {'name': 'vsDataMtp3bSpItu', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 308},
        {'name': 'vsDataMtp3bSr', 'parent_pk': 310, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 309},
        {'name': 'vsDataMtp3bSrs', 'parent_pk': 308, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 310},
        {'name': 'vsDataMultiCarrier', 'parent_pk': 171, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 311},
        {'name': 'vsDataMultiErabsPerUser', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 312},
        {'name': 'vsDataNbapCommon', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 313},
        {'name': 'vsDataNbapDedicated', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 314},
        {'name': 'vsDataNetconfSsh', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 315},
        {'name': 'vsDataNetconfTls', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 316},
        {'name': 'vsDataNextHop', 'parent_pk': 317, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 317},
        {'name': 'vsDataNniSaalProfile', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 318},
        {'name': 'vsDataNodeBFunction', 'parent_pk': 27, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 320},
        {'name': 'vsDataNodeBLocalCell', 'parent_pk': 322, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 321},
        {'name': 'vsDataNodeBLocalCellGroup', 'parent_pk': 27, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 322},
        {'name': 'vsDataNodeBSectorCarrier', 'parent_pk': 321, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 323},
        {'name': 'vsDataNodeCredential', 'parent_pk': 110, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 324},
        {'name': 'vsDataNodeSupport', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 327},
        {'name': 'vsDataUeTac', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 572},
        {'name': 'vsDataNtpFrequencySync', 'parent_pk': 329, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 330},
        {'name': 'vsDataOs155SpiTtp', 'parent_pk': 188, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 340},
        {'name': 'vsDataPeerIPv4', 'parent_pk': 234, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 349},
        {'name': 'vsDataNtpServer', 'parent_pk': 531, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 331},
        {'name': 'vsDataQueue', 'parent_pk': 583, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 380},
        {'name': 'vsDataOamAccessPoint', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 332},
        {'name': 'vsDataRbsUnit', 'parent_pk': 164, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 395},
        {'name': 'vsDataReportConfigA1', 'parent_pk': 594, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 401},
        {'name': 'vsDataOamTrafficClass', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 333},
        {'name': 'vsDataOctAntUlPerfPkg', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 334},
        {'name': 'vsDataOperatorDefinedQci', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 336},
        {'name': 'vsDataOpProfiles', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 337},
        {'name': 'vsDataOptionalFeatureLicense', 'parent_pk': 274, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 338},
        {'name': 'vsDataOptionalFeatures', 'parent_pk': 274, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 339},
        {'name': 'vsDataOtdoaSupl', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 341},
        {'name': 'vsDataPacketFrequencySyncRef', 'parent_pk': 518, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 342},
        {'name': 'vsDataPaging', 'parent_pk': 343, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 343},
        {'name': 'vsDataPch', 'parent_pk': 32, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 344},
        {'name': 'vsDataPci', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 345},
        {'name': 'vsDataPcpSetToQueue', 'parent_pk': 347, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 346},
        {'name': 'vsDataPcpToQueueMap', 'parent_pk': 376, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 347},
        {'name': 'vsDataPdrDevice', 'parent_pk': 632, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 348},
        {'name': 'vsDataPfs', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 350},
        {'name': 'vsDataPiuDevice', 'parent_pk': 354, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 351},
        {'name': 'vsDataPlmn', 'parent_pk': 67, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 352},
        {'name': 'vsDataPlmnIdentityGroup', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 353},
        {'name': 'vsDataPlugInUnit', 'parent_pk': 494, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 354},
        {'name': 'vsDataPm', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 355},
        {'name': 'vsDataPmEventM', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 356},
        {'name': 'vsDataPmEventService', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 357},
        {'name': 'vsDataPmInitiatedUeMeasurements', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 358},
        {'name': 'vsDataPmMeasurementCapabilities', 'parent_pk': 355, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 359},
        {'name': 'vsDataPmService', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 360},
        {'name': 'vsDataPmSupport', 'parent_pk': 327, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 361},
        {'name': 'vsDataPositioningServiceClass', 'parent_pk': 564, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 363},
        {'name': 'vsDataPowerControl', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 364},
        {'name': 'vsDataPowerDistribution', 'parent_pk': 158, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 365},
        {'name': 'vsDataPowerSupply', 'parent_pk': 158, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 366},
        {'name': 'vsDataPredefRbsScannerGpeh', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 367},
        {'name': 'vsDataPreschedulingProfile', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 368},
        {'name': 'vsDataProcessorLoad', 'parent_pk': 369, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 369},
        {'name': 'vsDataPtp', 'parent_pk': 553, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 370},
        {'name': 'vsDataPtpBcOcPort', 'parent_pk': 82, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 371},
        {'name': 'vsDataPws', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 372},
        {'name': 'vsDataQciProfilePredefined', 'parent_pk': 374, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 373},
        {'name': 'vsDataQciTable', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 374},
        {'name': 'vsDataQosAwareScheduler', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 375},
        {'name': 'vsDataQoSClassifier', 'parent_pk': 625, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 376},
        {'name': 'vsDataQosPolicy', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 377},
        {'name': 'vsDataQosProfiles', 'parent_pk': 553, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 378},
        {'name': 'vsDataQuadAntUlPerfPkg', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 379},
        {'name': 'vsDataRabHandling', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 381},
        {'name': 'vsDataRach', 'parent_pk': 32, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 382},
        {'name': 'vsDataRadioBearerTable', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 383},
        {'name': 'vsDataRadioEquipmentClock', 'parent_pk': 518, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 384},
        {'name': 'vsDataRadioLinks', 'parent_pk': 321, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 386},
        {'name': 'vsDataRadioUnitCascading', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 387},
        {'name': 'vsDataRanap', 'parent_pk': 267, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 388},
        {'name': 'vsDataRateShaping', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 389},
        {'name': 'vsDataRbsLocalCell', 'parent_pk': 27, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 390},
        {'name': 'vsDataRbsMeasControl', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 391},
        {'name': 'vsDataRbsSlot', 'parent_pk': 393, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 392},
        {'name': 'vsDataRbsSubrack', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 393},
        {'name': 'vsDataRbsSynchronization', 'parent_pk': 27, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 394},
        {'name': 'vsDataRcs', 'parent_pk': 396, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 396},
        {'name': 'vsDataRdiPort', 'parent_pk': 393, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 397},
        {'name': 'vsDataRealTimeSecLog', 'parent_pk': 481, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 398},
        {'name': 'vsDataRedirectWithNacc', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 399},
        {'name': 'vsDataReliableProgramUniter', 'parent_pk': 634, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 400},
        {'name': 'vsDataReportConfigA1Prim', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 402},
        {'name': 'vsDataReportConfigA1Sec', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 403},
        {'name': 'vsDataReportConfigA4', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 404},
        {'name': 'vsDataReportConfigA5', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 405},
        {'name': 'vsDataReportConfigA5Anr', 'parent_pk': 405, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 406},
        {'name': 'vsDataReportConfigA5SoftLock', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 407},
        {'name': 'vsDataReportConfigA5UlTrig', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 408},
        {'name': 'vsDataReportConfigB1Geran', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 409},
        {'name': 'vsDataVendorCredential', 'parent_pk': 110, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 589},
        {'name': 'vsDataRlcUm', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 449},
        {'name': 'vsDataRncConfigLimits', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 450},
        {'name': 'vsDataRetSubUnit', 'parent_pk': 65, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 442},
        {'name': 'vsDataReportConfigB2CdmaUlTrig', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 414},
        {'name': 'vsDataReportConfigB2Geran', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 415},
        {'name': 'vsDataReportConfigB2GeranUlTrig', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 416},
        {'name': 'vsDataReportConfigB2Utra', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 417},
        {'name': 'vsDataReportConfigB2UtraUlTrig', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 418},
        {'name': 'vsDataReportConfigCsfbCdma2000', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 419},
        {'name': 'vsDataReportConfigCsfbGeran', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 420},
        {'name': 'vsDataReportConfigCsfbUtra', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 421},
        {'name': 'vsDataReportConfigCsg', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 422},
        {'name': 'vsDataReportConfigEUtraBadCovPrim', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 423},
        {'name': 'vsDataReportConfigEUtraBadCovSec', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 424},
        {'name': 'vsDataReportConfigEUtraBestCell', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 425},
        {'name': 'vsDataReportConfigEUtraBestCellAnr', 'parent_pk': 425, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 426},
        {'name': 'vsDataReportConfigEUtraIFA3UlTrig', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 427},
        {'name': 'vsDataReportConfigEUtraIFBestCell', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 428},
        {'name': 'vsDataReportConfigEUtraInterFreqLb', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 429},
        {'name': 'vsDataReportConfigEUtraInterFreqMbms', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2,
         'modified_by': 0, 'added_by': 0, 'pk': 430},
        {'name': 'vsDataReportConfigEUtraIntraFreqPm', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 431},
        {'name': 'vsDataReportConfigInterRatLb', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 432},
        {'name': 'vsDataReportConfigSCellA1A2', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 433},
        {'name': 'vsDataReportConfigSCellA4', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 434},
        {'name': 'vsDataReportConfigSCellA6', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 435},
        {'name': 'vsDataReportConfigSearch', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 436},
        {'name': 'vsDataResMeasControl', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 437},
        {'name': 'vsDataRetCascading', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 438},
        {'name': 'vsDataRetConfigurationMgt', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 439},
        {'name': 'vsDataRetDevice', 'parent_pk': 441, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 440},
        {'name': 'vsDataRetDeviceSet', 'parent_pk': 444, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 441},
        {'name': 'vsDataRetSupport', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 443},
        {'name': 'vsDataRetuDeviceGroup', 'parent_pk': 77, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 444},
        {'name': 'vsDataRfBranch', 'parent_pk': 65, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 445},
        {'name': 'vsDataRfPort', 'parent_pk': 393, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 446},
        {'name': 'vsDataRiPort', 'parent_pk': 393, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 448},
        {'name': 'vsDataRncFeature', 'parent_pk': 274, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 451},
        {'name': 'vsDataRncFunction', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 452},
        {'name': 'vsDataRncModule', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 453},
        {'name': 'vsDataRnlQosClassProfile', 'parent_pk': 454, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 454},
        {'name': 'vsDataRnsap', 'parent_pk': 268, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 455},
        {'name': 'vsDataROHC', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 456},
        {'name': 'vsDataRouter', 'parent_pk': 553, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 457},
        {'name': 'vsDataRouteTableIPv4Static', 'parent_pk': 458, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 458},
        {'name': 'vsDataRoutingArea', 'parent_pk': 279, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 459},
        {'name': 'vsDataRoutingTable', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 460},
        {'name': 'vsDataRps', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 461},
        {'name': 'vsDataRrc', 'parent_pk': 462, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 462},
        {'name': 'vsDataRruDeviceGroup', 'parent_pk': 393, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 463},
        {'name': 'vsDataRttPositioning', 'parent_pk': 564, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 464},
        {'name': 'vsDataS1HODataFwd', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 465},
        {'name': 'vsDataSasPositioning', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 466},
        {'name': 'vsDataSccpApLocal', 'parent_pk': 469, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 467},
        {'name': 'vsDataSccpApRemote', 'parent_pk': 469, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 468},
        {'name': 'vsDataSccpScrc', 'parent_pk': 470, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 469},
        {'name': 'vsDataSccpSp', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 470},
        {'name': 'vsDataSchema', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 472},
        {'name': 'vsDataSctp', 'parent_pk': 473, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 473},
        {'name': 'vsDataSctpAssociation', 'parent_pk': 475, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 474},
        {'name': 'vsDataSctpEndpoint', 'parent_pk': 553, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 475},
        {'name': 'vsDataSctpProfile', 'parent_pk': 553, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 476},
        {'name': 'vsDataSecM', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 477},
        {'name': 'vsDataSector', 'parent_pk': 27, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 478},
        {'name': 'vsDataSectorAntenna', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 479},
        {'name': 'vsDataSectorCarrier', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 480},
        {'name': 'vsDataSecurity', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 481},
        {'name': 'vsDataSecurityHandling', 'parent_pk': 482, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 482},
        {'name': 'vsDataServiceArea', 'parent_pk': 279, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 483},
        {'name': 'vsDataServiceSpecificDRX', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 484},
        {'name': 'vsDataServiceTriggeredMobility', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 485},
        {'name': 'vsDataSfpModule', 'parent_pk': 614, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 486},
        {'name': 'vsDataSftp', 'parent_pk': 196, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 487},
        {'name': 'vsDataShaper', 'parent_pk': 625, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 488},
        {'name': 'vsDataSharedNetworkSupport', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 489},
        {'name': 'vsDataDifferentiatedAdmissionControl', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2,
         'modified_by': 0, 'added_by': 0, 'pk': 610},
        {'name': 'vsDataSubscriberProfileID', 'parent_pk': 160, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 506},
        {'name': 'vsDataSyncServer', 'parent_pk': 549, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 520},
        {'name': 'vsDataTimeSyncIO', 'parent_pk': 549, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 533},
        {'name': 'vsDataTrafficScheduler', 'parent_pk': 172, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 551},
        {'name': 'vsDataSingLayBeamfPerfPkg', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 492},
        {'name': 'vsDataSite', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 493},
        {'name': 'vsDataSlot', 'parent_pk': 505, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 494},
        {'name': 'vsDataSnmp', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 495},
        {'name': 'vsDataSnmpTargetV2C', 'parent_pk': 495, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 496},
        {'name': 'vsDataSnmpTargetV3', 'parent_pk': 495, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 497},
        {'name': 'vsDataSpidHoWhiteList', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 498},
        {'name': 'vsDataSpidRATFreqPrio', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 499},
        {'name': 'vsDataSpiQosClass', 'parent_pk': 500, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 500},
        {'name': 'vsDataSTN', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 502},
        {'name': 'vsDataStnFunction', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 503},
        {'name': 'vsDataStreamingCapabilities', 'parent_pk': 178, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 504},
        {'name': 'vsDataSubrack', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 505},
        {'name': 'vsDataSubscrProfileIdHandling', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 507},
        {'name': 'vsDataSupport12Cells', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 508},
        {'name': 'vsDataSupport6Cells', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 509},
        {'name': 'vsDataSwAllocation', 'parent_pk': 634, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 510},
        {'name': 'vsDataSwInventory', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 511},
        {'name': 'vsDataSwitchCoreUnit', 'parent_pk': 354, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 512},
        {'name': 'vsDataSwitchInternalLinkPort', 'parent_pk': 512, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 513},
        {'name': 'vsDataSwitchPortStp', 'parent_pk': 164, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 514},
        {'name': 'vsDataSwitchStp', 'parent_pk': 180, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 515},
        {'name': 'vsDataSwM', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 516},
        {'name': 'vsDataSwVersion', 'parent_pk': 511, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 517},
        {'name': 'vsDataSynchronization', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 518},
        {'name': 'vsDataSyncPort', 'parent_pk': 614, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 519},
        {'name': 'vsDataSysM', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 521},
        {'name': 'vsDataSystemFunctions', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 522},
        {'name': 'vsDataTCPOptimization', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 523},
        {'name': 'vsDataTdScdmaSessionContinuity', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 524},
        {'name': 'vsDataTempSensor', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 525},
        {'name': 'vsDataTermPointToENB', 'parent_pk': 181, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 526},
        {'name': 'vsDataTermPointToMme', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 527},
        {'name': 'vsDataTimeM', 'parent_pk': 521, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 529},
        {'name': 'vsDataTimeServer', 'parent_pk': 518, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 530},
        {'name': 'vsDataTimeSetting', 'parent_pk': 522, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 531},
        {'name': 'vsDataTimeSettings', 'parent_pk': 327, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 532},
        {'name': 'vsDataTimingUnit', 'parent_pk': 534, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 534},
        {'name': 'vsDataTls', 'parent_pk': 477, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 535},
        {'name': 'vsDataTm7ModeSwitching', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 536},
        {'name': 'vsDataTmaSupport', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 537},
        {'name': 'vsDataTnApplication', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 538},
        {'name': 'vsDataTnlCchQosClassProfile', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 539},
        {'name': 'vsDataTnlHspaQosClassProfile', 'parent_pk': 381, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 540},
        {'name': 'vsDataTnlIuQosClassProfile', 'parent_pk': 381, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 541},
        {'name': 'vsDataTnlQosClass', 'parent_pk': 539, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 542},
        {'name': 'vsDataTnPort', 'parent_pk': 614, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 543},
        {'name': 'vsDataTpaDevice', 'parent_pk': 392, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 544},
        {'name': 'vsDataTpaDeviceSet', 'parent_pk': 392, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 545},
        {'name': 'vsDataTrafficAwarePowerSave', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 546},
        {'name': 'vsDataTrafficClass', 'parent_pk': 635, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 547},
        {'name': 'vsDataTrafficClassPsInt', 'parent_pk': 69, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 548},
        {'name': 'vsDataTrafficManagement', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 549},
        {'name': 'vsDataTrafficManager', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 550},
        {'name': 'vsDataTransceiver', 'parent_pk': 131, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 552},
        {'name': 'vsDataTransport', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 553},
        {'name': 'vsDataTransportNetwork', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 554},
        {'name': 'vsDataTrustedCertificate', 'parent_pk': 110, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 556},
        {'name': 'vsDataTtiBundling', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 557},
        {'name': 'vsDataTuSyncRef', 'parent_pk': 558, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 558},
        {'name': 'vsDataTwampResponder', 'parent_pk': 553, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 559},
        {'name': 'vsDataTxDataCloning', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 560},
        {'name': 'vsDataTxDeviceGroup', 'parent_pk': 351, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 561},
        {'name': 'vsDataUeMeasControl', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 562},
        {'name': 'vsDataUePosCellId', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 563},
        {'name': 'vsDataUePositioning', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 564},
        {'name': 'vsDataUeRabType', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 565},
        {'name': 'vsDataUeRc', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 566},
        {'name': 'vsDataUeRcEdchFlow', 'parent_pk': 566, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 567},
        {'name': 'vsDataUeRcPhyChEdch', 'parent_pk': 566, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 568},
        {'name': 'vsDataUeRcRab', 'parent_pk': 566, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 569},
        {'name': 'vsDataUeRcTrCh', 'parent_pk': 566, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 570},
        {'name': 'vsDataUeRrcType', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 571},
        {'name': 'vsDataSignalingRadioBearer', 'parent_pk': 383, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 491},
        {'name': 'vsDataUniSaalTp', 'parent_pk': 586, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 577},
        {'name': 'vsDataVc4Ttp', 'parent_pk': 360, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 587},
        {'name': 'vsDataWifiModule', 'parent_pk': 418, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 602},
        {'name': 'vsDataEquipmentClockReference', 'parent_pk': 406, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 612},
        {'name': 'vsDataIpAtmLink', 'parent_pk': 253, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 617},
        {'name': 'vsDataUlFss', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 574},
        {'name': 'vsDataUlPrbCapacity', 'parent_pk': 99, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 575},
        {'name': 'vsDataUniSaalProfile', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 576},
        {'name': 'vsDataUpgradeTrace', 'parent_pk': 634, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 578},
        {'name': 'vsDataUra', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 579},
        {'name': 'vsDataUserIdentity', 'parent_pk': 581, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 580},
        {'name': 'vsDataUserManagement', 'parent_pk': 477, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 581},
        {'name': 'vsDataUtranCellRelation', 'parent_pk': 584, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 582},
        {'name': 'vsDataUtraNetwork', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 583},
        {'name': 'vsDataUtranFreqRelation', 'parent_pk': 172, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 584},
        {'name': 'vsDataUtranNetwork', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 585},
        {'name': 'vsDataUtranRelation', 'parent_pk': 33, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 586},
        {'name': 'vsDataVclTp', 'parent_pk': 593, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 588},
        {'name': 'vsDataVLAN', 'parent_pk': 165, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 590},
        {'name': 'vsDataVLANGroup', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 591},
        {'name': 'vsDataVlanPort', 'parent_pk': 494, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 592},
        {'name': 'vsDataVpcTp', 'parent_pk': 594, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 593},
        {'name': 'vsDataVplTp', 'parent_pk': 607, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 594},
        {'name': 'vsDataVrrpv3Interface', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 595},
        {'name': 'vsDataVrrpv3Session', 'parent_pk': 234, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 596},
        {'name': 'vsDataVswrSupervision', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 597},
        {'name': 'vsDataWcdmaCarrier', 'parent_pk': 268, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 598},
        {'name': 'vsDataWcdmaHandover', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 599},
        {'name': 'vsDataWcdmaSessionContinuity', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 600},
        {'name': 'vsDataWifiMobility', 'parent_pk': 29, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 601},
        {'name': 'vsDataXpProgram', 'parent_pk': 393, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 603},
        {'name': 'AlarmIRP', 'parent_pk': 22, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0, 'pk': 604},
        {'name': 'ExternalUtranCell', 'parent_pk': 30, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 605},
        {'name': 'vsDataAgpsPositioning', 'parent_pk': 564, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 606},
        {'name': 'vsDataAtmPort', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 607},
        {'name': 'vsDataAtmTrafficDescriptor', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 608},
        {'name': 'vsDataCapacityConnectedUsers', 'parent_pk': 99, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 609},
        {'name': 'vsDataDlBasebandCapacity', 'parent_pk': 99, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 611},
        {'name': 'vsDataFeatureKey', 'parent_pk': 276, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 613},
        {'name': 'vsDataFieldReplaceableUnit', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 614},
        {'name': 'vsDataFilePullCapabilities', 'parent_pk': 178, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 615},
        {'name': 'vsDataImeisvTable', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 616},
        {'name': 'vsDataIpv4Peer', 'parent_pk': 254, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 618},
        {'name': 'vsDataIpv4StaticRoute', 'parent_pk': 260, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 619},
        {'name': 'vsDataIubEdch', 'parent_pk': 23, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 620},
        {'name': 'vsDataMulticastAntennaBranch', 'parent_pk': 65, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 621},
        {'name': 'vsDataNodeGroupSyncMember', 'parent_pk': 384, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 622},
        {'name': 'vsDataNonPlannedPciDrxProfile', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 623},
        {'name': 'vsDataPmUlInterferenceReport', 'parent_pk': 480, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 624},
        {'name': 'vsDataQueueSystem', 'parent_pk': 163, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 625},
        {'name': 'vsDataRbsEventStreamer', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 626},
        {'name': 'vsDataReportConfigA5DlComp', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 627},
        {'name': 'vsDataResourcePartitions', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 628},
        {'name': 'vsDataRlfProfile', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 629},
        {'name': 'vsDataRncCapacity', 'parent_pk': 274, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 630},
        {'name': 'vsDataSectorEquipmentFunction', 'parent_pk': 327, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 631},
        {'name': 'vsDataSpDevicePool', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 632},
        {'name': 'vsDataSwItem', 'parent_pk': 511, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 633},
        {'name': 'vsDataSwManagement', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 634},
        {'name': 'vsDataTnlDchQosClassProfile', 'parent_pk': 381, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 635},
        {'name': 'vsDataUlBasebandCapacity', 'parent_pk': 99, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 636},
        {'name': 'vsDataUtranCell', 'parent_pk': 32, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 637},
        {'name': 'vsDataVRF', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 638},
        {'name': 'vsDataUlCompGroup', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 573},
        {'name': 'SubNetwork', 'parent_pk': 16, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 30},
        {'name': 'vsDataAddressIPv4', 'parent_pk': 234, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 44},
        {'name': 'vsDataAirIfLoadGenerator', 'parent_pk': 339, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 49},
        {'name': 'vsDataAnrIafUtran', 'parent_pk': 54, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 60},
        {'name': 'vsDataAal2QosCodePointProfile', 'parent_pk': 554, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 38},
        {'name': 'vsDataBrmBackup', 'parent_pk': 88, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 85},
        {'name': 'vsDataRiLink', 'parent_pk': 156, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 447},
        {'name': 'RncFunction', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 29},
        {'name': 'vsDataBrmBackupHousekeeping', 'parent_pk': 88, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 86},
        {'name': 'vsDataBrmCalendarBasedPeriodicEvent', 'parent_pk': 89, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 90},
        {'name': 'vsDataCarrierAggregationFunction', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 102},
        {'name': 'vsDataDownlinkBaseBandPool', 'parent_pk': 505, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 136},
        {'name': 'vsDataEthernetBridgePort', 'parent_pk': 167, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 160},
        {'name': 'vsDataEthernetSwitchFabric', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 165},
        {'name': 'vsDataEthernetSwitchingAdm', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 166},
        {'name': 'vsDataExternalENodeBFunction', 'parent_pk': 152, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 181},
        {'name': 'vsDataGeranFreqGroupRelation', 'parent_pk': 172, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 209},
        {'name': 'vsDataIpAccessHostSpb', 'parent_pk': 259, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 244},
        {'name': 'vsDataIpEthPacketDataRouter', 'parent_pk': 348, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 246},
        {'name': 'vsDataIpFlowMonitor', 'parent_pk': 249, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 247},
        {'name': 'vsDataKeyFileInformation', 'parent_pk': 270, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 269},
        {'name': 'vsDataMeasurementDefinition', 'parent_pk': 502, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 295},
        {'name': 'vsDataNodeManagementFunction', 'parent_pk': 24, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 326},
        {'name': 'vsDataNodeSynch', 'parent_pk': 23, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 328},
        {'name': 'vsDataNtp', 'parent_pk': 553, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0, 'added_by': 0,
         'pk': 329},
        {'name': 'vsDataOnSiteActivities', 'parent_pk': 327, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 335},
        {'name': 'vsDataPmUeMeasControl', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 362},
        {'name': 'vsDataRadioEquipmentClockReference', 'parent_pk': 384, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 385},
        {'name': 'vsDataReportConfigB1Utra', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 410},
        {'name': 'vsDataReportConfigB2Cdma2000', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 411},
        {'name': 'vsDataReportConfigB2Cdma20001xRtt', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 412},
        {'name': 'vsDataReportConfigB2CdmaRttUlTrig', 'parent_pk': 562, 'vendor_pk': 1, 'tech_pk': 2, 'modified_by': 0,
         'added_by': 0, 'pk': 413},
    ])

    op.execute("""ALTER SEQUENCE seq_managedobjects_pk RESTART WITH {};""".format(639))

def downgrade():
    op.execute("""DELETE FROM managedobjects WHERE vendor_pk = {0} AND tech_pk = {1}""".format(1, 2))
