"""Create Nokia 2G CM data tables

Revision ID: 63f20accf576
Revises: 5113d319b861
Create Date: 2018-02-11 00:08:58.552000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '63f20accf576'
down_revision = '5113d319b861'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('adce',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('frequencyBandInUse', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsMsTxPwrMaxCCH1x00', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msTxPwrMaxGSM1x00', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('targetCellDN', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adjCellBsicBcc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adjCellBsicNcc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adjacentCellIdCI', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adjacentCellIdLac', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adjacentCellIdMCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adjacentCellIdMNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adjcIndex', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrDadlbTargetCell', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bcchFrequency', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('chainedAdjacentCell', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dadlbTargetCell', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('drThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enableDerivedHandoverPower', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enableHoMarginLevQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsEnabled', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsMsTxpwrMaxCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsPenaltyTime', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsRxlevAccessMin', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsTemporaryOffset', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hcsPriorityClass', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hcsThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoLevelUmbrella', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoLoadFactor', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoMarginDelayTime', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoMarginLev', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoMarginPbgt', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoMarginQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoPriorityLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTargetArea', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msTxPwrMaxGSM', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('neighbourCellRanking', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rac', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxLevMinCell', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('synchronized', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('trhoTargetLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('adjl',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('barredLteAdjCellGroup', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('barredLteAdjCellList', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('barredLteAdjCellPattern', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('barredLteAdjCellPatternSense', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('earfcn', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lteAdjCellMcc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lteAdjCellMinBand', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lteAdjCellMinRxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lteAdjCellMnc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lteAdjCellPriority', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lteAdjCellReselectLowerThr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lteAdjCellReselectUpperThr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lteAdjCellTac', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('adjw',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('targetCellDN', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('AdjwCId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('intSystemDaEcioThr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lac', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('mcc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('minEcnoThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('mnc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rncId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('sac', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('scramblingCode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('txDiversityInd', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('uarfcn', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('bcf',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('latitude', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('longitude', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('autoUnlAllowed', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('batteryBackupProcedure', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bcchTrxBatbuTimer', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bcfOutputInUse', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bcfType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('clockSource', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('externalAlarmDefinition_inputId_inputTextId_polarity_reportingR', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lapdLinkName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lapdLinkNumber', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('masterClockBcf', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('normTrxBatbuTimer', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxDifferenceLimit', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('syncMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('synchEnabled', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('synchStatus', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('outputDefinition_textId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('notificationOrigin', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('bsc',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bscOptions', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('dcsMacrocellThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dcsMicrocellThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('neSwRelease', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adjCellFreqsInMeasBAInfo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('alrmChFail', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('alrmNoOfSei', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('alrmSchFail', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('alrmSdcch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('alrmSeizReq', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('alrmTch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhLowerLoadThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhMaxLoadOfTgtCell', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhTrhoGuardTime', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhUpperLoadThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfInHandovers', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrSetGradesEnabl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ansiEnvironment', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('batteryBackupTimer', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bcsuLoadThr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bscType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('btsLoadDepTchRateLower', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('btsLoadDepTchRateUpper', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('callReleaseLimit', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('delayHoPcEmergencyCalls', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dfcaAmrFrConnection_softBlockingCn', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dfcaAmrHrConnection_softBlockingCn', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dfcaFrConnection_softBlockingCn', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('disableExtDr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('disableIntHo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dtmFragmentationPenalty', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('emerCallOnFacch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('extraTrxBcsuNumber', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('extraTrxMaxTrxInBcsu', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('fepInPcHoUse', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('frTchALim', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('freeTSLsCsDowngrade', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('freeTSLsCsUpgrade', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('freqInMeasBAInfo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsTerritoryCalc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gsmMacrocellThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gsmMicrocellThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoPrefOrderInterfDl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoPrefOrderInterfUl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hrTchALim', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('inactCriteria', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('inactEventsPerHour', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('incomeRateThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('initAmrChannelRate', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('internalHoToExternal', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('intraSegSdcchHoGuard', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ishoPreferredForNonDtmMs', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lapdLoadThr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('loadRateChSearch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxBcfCapacity', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxBtsCapacity', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxHldSdcch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxHldTch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxOnHiIf', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxTchTransactionRate', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxTrxCapacityHw', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxTrxCapacityReal', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('meanBepLimitUL_Prof0_2tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('meanBepLimitUL_Prof0_3tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('meanBepLimitUL_Prof0_4tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('meanBepLimitUL_Prof1_2tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('meanBepLimitUL_Prof1_3tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('meanBepLimitUL_Prof1_4tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('meanBepLimitUL_Prof2_3tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('meanBepLimitUL_Prof2_4tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('measPrdCh', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('measPrdFail', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('measPrdSdcch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('measTchMhold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('minHiIf', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('minHldTch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msDistanceBehaviour', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msSpeedC11', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msSpeedC12', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('noOfPrefCells', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nokBtsOffHour', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nokBtsOffMinute', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nokBtsOnHour', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nokBtsOnMinute', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ordinaryCallOnFacch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pagingAnsOnFacch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuMaxNoDLtbfInCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuMaxNoULtbfInCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcAckBlerLimit_legacyStream', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcAckBlerLimit_limit10004000ms', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcAckBlerLimit_limit10150ms', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcAckBlerLimit_limit200950ms', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcAckBlerLimit_notAvailable', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcUnackBlerLimit_legacyStream', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcUnackBlerLimit_limit110e1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcUnackBlerLimit_limit110e2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcUnackBlerLimit_limit110e3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcUnackBlerLimit_limit710e3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pfcUnackBlerLimit_notAvailable', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('prdHighIf', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('prdNokBts', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qcActionTriggerThr_drop', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qcActionTriggerThr_nccr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qcActionTriggerThr_qosRenego', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qcActionTriggerThr_realloca', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('reestablishOnFacch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rnwConfId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rnwFallbackConfId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rnwPlanConfId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rnwPlanDatabaseState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rtsl0PrefInTCHAlloc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxAntSupPer', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxLevBalance', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxLevelBasedTchAccess', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxqualLimitUL_Prof0_2tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxqualLimitUL_Prof0_3tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxqualLimitUL_Prof0_4tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxqualLimitUL_Prof1_2tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxqualLimitUL_Prof1_3tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxqualLimitUL_Prof1_4tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxqualLimitUL_Prof2_3tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxqualLimitUL_Prof2_4tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('sacchRepeatWindow', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('saicDlCIOffset', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedStepSizeDlHighPrior', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedStepSizeDlLowPrior', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedStepSizeDlNormPrior', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedStepSizeUlPrior1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedStepSizeUlPrior2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedStepSizeUlPrior3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedStepSizeUlPrior4', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_backgroundARP1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_backgroundARP2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_backgroundARP3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_interactive1ARP1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_interactive1ARP2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_interactive1ARP3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_interactive2ARP1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_interactive2ARP2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_interactive2ARP3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_interactive3ARP1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_interactive3ARP2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_interactive3ARP3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_streamingARP1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_streamingARP2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('schedulingWeight_streamingARP3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('sdcchAlLimit', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('signallingPointCodeIN0', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('signallingPointCodeIN1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('signallingPointCodeNA0', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('signallingPointCodeNA1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('slowAmrLaEnabled', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('supervisionPeriod', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('tchRateInternalHo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('tchTransactionCount', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('terrUpdGuardTGprs', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('triggerMeasPeriod', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('variableDlStepSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('wcdmaRanSaiPenalty', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('bts',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('notAllowedAccessClasses', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('plmnPermitted', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('frequencyBandInUse', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsMsTxPwrMaxCCH1x00', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('minMsTxPower', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msTxPwrMaxCCH1x00', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msTxPwrMaxGSM1x00', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('angle', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cellType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('insiteGateway', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adaptiveLaAlgorithm', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('allowIMSIAttachDetach', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhLowerLoadThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhMaxLoadOfTgtCell', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhTrhoGuardTime', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhUpperLoadThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrCodecModeSet', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrDlThreshold1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrDlThreshold2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrDlThreshold3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrHysteresis1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrHysteresis2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrHysteresis3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrInitCodecMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrStartMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrUlThreshold1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrUlThreshold2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfFrUlThreshold3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrCodecModeSet', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrDlThreshold1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrDlThreshold2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrDlThreshold3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrHysteresis1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrHysteresis2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrHysteresis3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrInitCodecMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrStartMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrUlThreshold1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrUlThreshold2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrConfHrUlThreshold3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrHoFrInHoThrDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrHoFrThrDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrHoFrThrUlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrHoHrInHoThrDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrHoHrThrDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrHoHrThrUlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrPocFrPcLThrDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrPocFrPcLThrUlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrPocFrPcUThrDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrPocFrPcUThrUlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrPocHrPcLThrDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrPocHrPcLThrUlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrPocHrPcUThrDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amrPocHrPcUThrUlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('antennaHopping', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bsIdentityCodeBCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bsIdentityCodeNCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('btsIsHopping', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('btsLoadInSeg', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('btsLoadThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('btsMeasAver', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('btsSpLoadDepTchRateLower', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('btsSpLoadDepTchRateUpper', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('callReestablishmentAllowed', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cellBarQualify', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cellBarred', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cellId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cellLoadForChannelSearch', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cellNumberInBtsHw', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cellReselectHysteresis', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cellReselectOffset', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cellReselectParamInd', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cnThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dedicatedGPRScapacity', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('defaultGPRScapacity', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('directGPRSAccessBts', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('diversityUsed', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dlNoiseLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('drInUse', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('drMethod', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dtxMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('earlySendingIndication', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('egprsEnabled', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('egprsInitMcsAckMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('egprsInitMcsUnAckMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('egprsLinkAdaptEnabled', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('egprsMaxBlerAckMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('egprsMaxBlerUnAckMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('egprsMeanBepOffset8psk', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('egprsMeanBepOffsetGmsk', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('emergencyCallRestricted', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('fddQMin', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('fddQOffset', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsEnabled', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsMsTxpwrMaxCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsNonBCCHRxlevLower', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsNonBCCHRxlevUpper', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsRxlevAccessMin', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gsmPriority', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hcsPriorityClass', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hcsThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoppingMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoppingSequenceNumber1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoppingSequenceNumber2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('idleStateBcchAllocListId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('inactEndTimeHour', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('inactEndTimeMinute', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('inactStartTimeHour', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('inactStartTimeMinute', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('inactWeekDays', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('csAckDl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('csAckUl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('csExtAckDl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('csExtAckUl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('csExtUnackDl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('csExtUnackUl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('csUnackDl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('csUnackUl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('initMcsExtAckMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('initMcsExtUnackMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('interferenceAveragingProcessAverPeriod', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('interferenceAveragingProcessBoundary0', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('interferenceAveragingProcessBoundary1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('interferenceAveragingProcessBoundary2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('interferenceAveragingProcessBoundary3', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('interferenceAveragingProcessBoundary4', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('interferenceAveragingProcessBoundary5', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('locationAreaIdLAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('locationAreaIdMCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('locationAreaIdMNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lowPriorityThr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maioOffset', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maioStep', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('masterBcf', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxGPRSCapacity', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxNumberOfRepetition', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxNumberRetransmission', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxQueueLength', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxTimeLimitDirectedRetry', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('measListUsedDuringMeas', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('measurementBCCHAllocation', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('minTimeLimitDirectedRetry', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msMaxDistInCallSetup', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msPriorityUsedInQueueing', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msTxPwrMaxCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msTxPwrMaxGSM', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('multiBandCell', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('multiBandCellReporting', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nbrOfSlotsSpreadTrans', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('newEstabCausesSupport', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('noOfBlocksForAccessGrant', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('noOfMFramesBetweenPaging', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nonBCCHLayerOffset', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nsei', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nwName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuCsHopping', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuCsNonHopping', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuDlBlerCpHopping', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuDlBlerCpNonHop', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuDlLaRiskLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuUlBlerCpHopping', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuUlBlerCpNonHop', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuUlLaRiskLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('penaltyTime', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('powerOffset', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('preferBCCHfreqGPRS2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('prioritySearchThr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('psei', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qSearchI', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qSearchP', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('queuePriorityNonUrgentHo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('queuePriorityUsed', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('queueingPriorityCall', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('queueingPriorityHandover', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('raReselectHysteresis', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rac', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('radioLinkTimeout', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('radioLinkTimeoutAmr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('radiusExtension', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('reselectionAlgorithmHysteresis', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxLevAccessMin', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('sectorId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('segmentId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('segmentName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('smsCbUsed', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('stircEnabled', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('tchRateIntraCellHo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('temporaryOffset', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('throughputFactor_cs1cs4dlcs', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('throughputFactor_cs1cs4ulcs', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('throughputFactor_mcs1mcs4ulcs', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('throughputFactor_mcs1mcs9dlcs', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('throughputFactor_mcs1mcs9ulcs', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('timeHysteresis', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('timeLimitCall', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('timeLimitHandover', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('timerPeriodicUpdateMs', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('trxPriorityInTchAlloc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ulNoiseLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('usedMobileAllocation', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('utranQualRxLevelMargin', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('utranThresholdReselection', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('wcdmaPriority', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('dap',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bcsuID', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('firstTSL', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lastTSL', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('logicalBCSUAddress', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcmCircuit_ID', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuID', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('psei', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('gpc',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qcTputThrModes_egprsDlRlcAckMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qcTputThrModes_egprsUlRlcAckMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qcTputThrModes_gprsDlRlcAckMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qcTputThrModes_gprsUlRlcAckMode', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('hoc',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('allAdjacentCellsAveraged', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('allUtranAdjAver', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhTrafficControlIUO', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhTrafficControlMCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('amhTrhoPbgtMargin', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('averagingWindowSizeAdjCell', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ddeThresholdsLevNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ddeThresholdsLevPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ddeThresholdsLevRxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ddeWindow', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enaFastAveCallSetup', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enaFastAveHo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enaFastAvePc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enaHierCellHo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enableIntraHoDl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enableIntraHoUl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enableMsDistance', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enablePowerBudgetHo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enableSddchHandover', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enableUmbrellaHo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('erfdEnabled', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('erfdOver', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('failMoveThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gsmPlmnPriorisation', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoAvaragingLevDLWeighting', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoAvaragingLevDlWindowSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoAveragingLevUlWeighting', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoAveragingLevUlWindowSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoAveragingQualDlWeighting', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoAveragingQualDlWindowSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoAveragingQualUlWeighting', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoAveragingQualUlWindowSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoPeriodPbgt', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoPeriodUmbrella', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTLDlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTLDlRxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTLUlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTLUlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTLUlRxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTQDlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTQDlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTQDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTQUlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTQUlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoTQUlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoThrInterferenceDlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoThrInterferenceDlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoThresholdsInterferenceDlRxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoThresholdsInterferenceULNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoThresholdsInterferenceULPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoThresholdsInterferenceULRxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoThresholdsLevDLNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoThresholdsRapidLevUl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('hoThresholdsRapidLevUlN', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('interSystemDa', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('intraHoLoRxLevLimAmrHr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('intraHoLoRxQualLimAmr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('intraHoUpRxLevLimAmrHr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxMsDistanceHoThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('minIntBetweenHoReq', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('minIntBetweenUnsuccHoAttempt', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('minIntUnsuccIsHo', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('minMsDistanceHoThreshold', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('modifiedAveWinNCell', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('modifiedNoz', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msDHoThrParamN8', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msDistanceAveragingParamHreqave', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msDistanceHoThresholdParamMsRangeMax', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('msDistanceHoThresholdParamP8', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('multiratRep', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('noOfZeroResUtran', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nonBcchLayerAccessThr', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nonBcchLayerExitThr_nx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nonBcchLayerExitThr_px', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('numberOfZeroResults', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('qSearchC', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('rxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('utranAveragingNumber', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('utranHoThScTpdc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('wcdmaRanCellPenalty', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('lapd',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('abisSigChannelSubSlot', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bitRate', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('abisSigChannelTimeSlotPcm', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('abisSigChannelTimeSlotTsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dChannelType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('logicalBCSUAddress', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('parameterSetNumber', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('sapi', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('tei', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('mal',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('frequency', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('frequencyBandInUse', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('nse',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuCapacity', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('localUdpPort', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nseType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('psei', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('nsvl',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dataWeight', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ipAddressValue', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ipAddressVersion', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('localUdpPort', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nsEntityId', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nsVirtualConnectionName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('preconfSgsnIpEpInd', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('psei', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('signWeight', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('udpPort', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('pcm',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('pcu',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('abisInType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bcsuID', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gbIfType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuAbisConnectionType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuID', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcuObjectState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('piuType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('psei', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('poc',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('alpha', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bepPeriod', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bsTxPwrMax', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bsTxPwrMax1x00', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bsTxPwrMin', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('enableAla', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gamma', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('maxPwrCompensation', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('minIntBetweenAla', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcALDlWeighting', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcALDlWindowSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcALUlWeighting', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcALUlWindowSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcAQLDlWeighting', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcAQLDlWindowSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcAQLUlWeighting', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcAQLUlWindowSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcControlEnabled', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcControlInterval', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcIncrStepSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTLevDlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTLevDlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTLevUlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTLevUlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTQual144Nx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTQual144Px', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTQual144RxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTQualDlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTQualDlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTQualDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTQualUlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTQualUlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLTQualUlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLowerThresholdsLevDLRxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcLowerThresholsLevULRxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcRedStepSize', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUTLevDlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUTLevDlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUTLevUlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUTLevUlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUTQualDlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUTQualDlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUTQualDlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUTQualUlNx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUTQualUlPx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUTQualUlRxQual', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUpperThresholdsLevDLRxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcUpperThresholdsLevULRxLevel', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('powerDecrQualFactor', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('powerLimitAla', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pwrDecrLimitBand0', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pwrDecrLimitBand1', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pwrDecrLimitBand2', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('tAvgT', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('tAvgW', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('ra',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('nseiList', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('routingAreaIdLac', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('routingAreaIdMcc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('routingAreaIdMnc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('routingAreaIdRac', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('smlc',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('tcsm',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('cardConfiguration_cardName_cardNumber', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('pcmConfiguration_pcmNumber_pcmType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('tcsmType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('tid',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('ioTextValue', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('tre',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('q1Address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('unitType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )
    op.create_table('trx',
    sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('dateTime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('version', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('distName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('id', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('address', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('name', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('adminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('bbUnitSupportsEdge', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel0AdminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel0Maio', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel0Pcm', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel0Subslot', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel0Tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel0Type', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel1AdminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel1Maio', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel1Pcm', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel1Subslot', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel1Tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel1Type', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel2AdminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel2Maio', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel2Pcm', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel2Subslot', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel2Tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel2Type', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel3AdminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel3Maio', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel3Pcm', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel3Subslot', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel3Tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel3Type', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel4AdminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel4Maio', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel4Pcm', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel4Subslot', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel4Tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel4Type', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel5AdminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel5Maio', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel5Pcm', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel5Subslot', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel5Tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel5Type', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel6AdminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel6Maio', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel6Pcm', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel6Subslot', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel6Tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel6Type', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel7AdminState', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel7Maio', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel7Pcm', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel7Subslot', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel7Tsl', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('channel7Type', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('daPool_ID', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('eTrxInd', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('gprsEnabledTrx', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('halfRateSupport', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('initialFrequency', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lapdLinkName', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('lapdLinkNumber', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('optimumRxLevDL', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('optimumRxLevUL', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('preferredBcchMark', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('subslotsForSignalling', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('trxAbilities', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('tsc', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('metroTrxType', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('notificationOrigin', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('numberOfTrxRfPowerLevels', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('trxOscCapability', sa.CHAR(length=250), autoincrement=False, nullable=True),
    sa.Column('trxRfPower', sa.CHAR(length=250), autoincrement=False, nullable=True),
    schema='nokia_cm_2g'
    )


def downgrade():
    op.drop_table('trx', schema='nokia_cm_2g')
    op.drop_table('tre', schema='nokia_cm_2g')
    op.drop_table('tid', schema='nokia_cm_2g')
    op.drop_table('tcsm', schema='nokia_cm_2g')
    op.drop_table('smlc', schema='nokia_cm_2g')
    op.drop_table('ra', schema='nokia_cm_2g')
    op.drop_table('poc', schema='nokia_cm_2g')
    op.drop_table('pcu', schema='nokia_cm_2g')
    op.drop_table('pcm', schema='nokia_cm_2g')
    op.drop_table('nsvl', schema='nokia_cm_2g')
    op.drop_table('nse', schema='nokia_cm_2g')
    op.drop_table('mal', schema='nokia_cm_2g')
    op.drop_table('lapd', schema='nokia_cm_2g')
    op.drop_table('hoc', schema='nokia_cm_2g')
    op.drop_table('gpc', schema='nokia_cm_2g')
    op.drop_table('dap', schema='nokia_cm_2g')
    op.drop_table('bts', schema='nokia_cm_2g')
    op.drop_table('bsc', schema='nokia_cm_2g')
    op.drop_table('bcf', schema='nokia_cm_2g')
    op.drop_table('adjw', schema='nokia_cm_2g')
    op.drop_table('adjl', schema='nokia_cm_2g')
    op.drop_table('adce', schema='nokia_cm_2g')
