"""Create tables for Huawei itf-N tables

Revision ID: 976340c0d321
Revises: f9286015dea6
Create Date: 2018-04-24 00:45:59.246000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '976340c0d321'
down_revision = 'f9286015dea6'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('NODE',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('SUBSESSION_NE',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column(' module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('SYS',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPORTRNCINPOOL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSCONTACT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSDESC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSLOCATION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSOBJECTID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSSERVICES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('U2GNCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDECN0THRESHHOLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERRATADJSQHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NIRATOVERLAP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRVCCSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TEMPOFFSET1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('U2GNCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UBCH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BANDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLKSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CCHCNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHETFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CFGRACIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DLTPCPATTERN01COUNT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPGID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DSSFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DSSSMALLCOVMAXTXPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXTXPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NEEDSELFPLANFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NINSYNCIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NOUTSYNCIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PRIORITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSCRAMBCODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REMARK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPGID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SSN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TIMER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRLFAILURE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TXDIVERSITYIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNDOWNLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINKIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VPLIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UCNOPERATOR',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPERATORNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPERATORTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UCNOPERGROUP',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPNUM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UEXT2GCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BANDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCCHARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CFGRACIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LDPRDRPRTSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBSCINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RATCELLTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPPSHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPRIMFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('USEOFHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UEXT3GCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORSAMECELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORUNCELLH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORUNCELLNOH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('APFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BANDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CFGRACIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCESUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EFACHSUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FASTHSCCACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HARQPREACAP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HCSPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HIGHRATERLACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXALLOWEDULTXPOWERIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MIDRATERLACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MOVEUSERPSLIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORHIGHRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORLOWRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORMIDRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OVERLAYMOBILITYFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSCRAMBCODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QQUALMININD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMININD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPDPCMODECHGFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TXDIVERSITYIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNDOWNLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINKIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('USEOFHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VPLIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXALLOWEDULTXPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QQUALMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMINEXTSUP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CP1SUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVMODFORDCHSDPA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPCHDIVMODFORMIMO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPCHDIVMODFOROTHER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FDPCHDIVMODFORMIMO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FDPCHDIVMODFOROTHER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('STTDSUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UEXT3GCELLINTRAFREQHO',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHORSCP1FTHRESHOLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HYSTFOR1A', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HYSTFOR1B', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HYSTFOR1C', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HYSTFOR1D', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HYSTFOR1F', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HYSTFOR1J', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRAABLTHDFOR1FECNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRAFREQFILTERCOEF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRAFREQMEASQUANTITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRARELTHDFOR1ACSNVP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRARELTHDFOR1ACSVP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRARELTHDFOR1APS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRARELTHDFOR1BCSNVP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRARELTHDFOR1BCSVP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRARELTHDFOR1BPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXCELLINACTIVESET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PERIODMRREPORTNUMFOR1A', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PERIODMRREPORTNUMFOR1C', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PERIODMRREPORTNUMFOR1J', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REPORTINTERVALFOR1A', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REPORTINTERVALFOR1C', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REPORTINTERVALFOR1J', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHOQUALMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRIGTIME1A', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRIGTIME1B', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRIGTIME1C', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRIGTIME1D', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRIGTIME1F', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRIGTIME1J', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('WEIGHT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UFACH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CHCODINGTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CODINGRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXCMCHPI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXFACHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXFACHPOWERUPOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MINCMCHPI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OFFSETFACHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RATEMATCHINGATTR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIGRBIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TOAWE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TOAWS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TTI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UINTERFREQNCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CLBFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDECN0THRESHHOLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDORLDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDTARGETULCOVERLIMITTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCELLSHUTDOWNFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOCOVPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERFREQADJSQHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERNCELLQUALREQFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UINTERNCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOQUALITYCONDITION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QQUALMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UINTRAFREQNCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLSFORBIDDEN1A', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLSFORBIDDEN1B', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCELLSHUTDOWNFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBMSNCELLIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UINTRANCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('ULAC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PLMNVALTAGMAX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PLMNVALTAGMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('ULOCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('ULTECELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLACKFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLPHYID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EUTRANCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTEARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTEBAND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPPSHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('U2LRIMCNOPERATORRTINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('ULTENCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ULTENCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UNBSC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBSCINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBSCNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UNODEB',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AUTOHOMINGFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DSSFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IPTRANSAPARTIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBPROTCLVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBTRACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSCMNGMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SATELLITEIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHARINGTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIGNALCREATETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SSN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TNLBEARERTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRANSDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UNODEBALGOPARA',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HSUPACECONSUMESELECTION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBBWCGSTTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBBWNONCGSTTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBREMAINBWTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBALGOENHSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBHSDPAMAXUSERNUM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBHSUPAMAXUSERNUM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UNODEBIP',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IPLOGPORTFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IPSN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IPSRN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBIPOAMIP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBIPOAMMASK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBTRANTP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SLAVENBIPOAMMASK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VLANFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VLANID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VLANPRI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UNODEPARA',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEINCMULTI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBAPNONSHARECPUOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBAPNONSHARERATIOTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('POOLLOADSHAREIURPDELAYTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RLACTTIMEINCMULTI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UNRNC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CSVOICEOVERHSPASUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPCSPDF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FUNCTIONSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HHORELOCPROCSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HHOTRIG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBCPPRIVATEINTERFACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBUPPRIVATEINTERFACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURCRSTVOICEDPCOVERSUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREXISTIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURHSDPASUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURHSUPASUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURMULTHSPASUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURPRIVATEINTERFACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURRLFAILSUSPSHODELTMR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURSMLESSCRSTVOICESUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURSRBOVEREDCHSUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPCSPDF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSBEPROCTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCPROTCLVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SERVICEIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHOTRIG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPCBITS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('STATEINDTMR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPIURCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TNLBEARERTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('WAMRSUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UNRNCRSVPARA',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVSWITCH0', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVU32PARA0', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVU32PARA1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UNRNCURA',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('URAID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UPCCPCH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UPCH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PCHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RATEMATCHINGATTR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TOAWE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TOAWS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UPCPICH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DSSSMALLCOVPCPICHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXPCPICHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MINPCPICHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PCPICHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UPICH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PICHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PICHMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('STTDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('UPSCH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSCHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('URAC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PLMNVALTAGMAX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PLMNVALTAGMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('URACH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MMAX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NB01MAX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NB01MIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RATEMATCHINGATTR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('USAC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('USMLC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSADDASSDATASENDFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSMEASLONGPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSMEASSHORTPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSMETHODTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLIDRTTMETHODTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EMERGLCSSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FORCEDSHOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRAFREQMEASPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUPCRSPTIMERLEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LCSWORKMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXGPSSATS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPTIONALIESENDSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OTDOAMETHODTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RESULTGEOTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SATELEVATIONCUTOFFANGLE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UTDOAMEASTIMERLEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

    op.create_table('USMLCCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSACTIVATEFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNAALTITUDEMETER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNALATITUDEDEGREE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNALONGITUDEDEGREE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNAOPENING', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNAORIENTATION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLAVERAGEHEIGHT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLENVIRONMENT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHEIGHTSTD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLIDRTTACTIVATEFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLLOCCFGTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCDF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXANTENNARANGE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MTRLGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OTDOAACTIVATEFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RXTXCHANDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TXCHANDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_umts'
    )

def downgrade():
    op.drop_table('NODE', schema='huawei_nbi_umts')
    op.drop_table('SUBSESSION_NE', schema='huawei_nbi_umts')
    op.drop_table('SYS', schema='huawei_nbi_umts')
    op.drop_table('U2GNCELL', schema='huawei_nbi_umts')
    op.drop_table('UBCH', schema='huawei_nbi_umts')
    op.drop_table('UCELL', schema='huawei_nbi_umts')
    op.drop_table('UCNOPERATOR', schema='huawei_nbi_umts')
    op.drop_table('UCNOPERGROUP', schema='huawei_nbi_umts')
    op.drop_table('UEXT2GCELL', schema='huawei_nbi_umts')
    op.drop_table('UEXT3GCELL', schema='huawei_nbi_umts')
    op.drop_table('UEXT3GCELLINTRAFREQHO', schema='huawei_nbi_umts')
    op.drop_table('UFACH', schema='huawei_nbi_umts')
    op.drop_table('UINTERFREQNCELL', schema='huawei_nbi_umts')
    op.drop_table('UINTRAFREQNCELL', schema='huawei_nbi_umts')
    op.drop_table('ULAC', schema='huawei_nbi_umts')
    op.drop_table('ULOCELL', schema='huawei_nbi_umts')
    op.drop_table('ULTECELL', schema='huawei_nbi_umts')
    op.drop_table('ULTENCELL', schema='huawei_nbi_umts')
    op.drop_table('UNBSC', schema='huawei_nbi_umts')
    op.drop_table('UNODEB', schema='huawei_nbi_umts')
    op.drop_table('UNODEBALGOPARA', schema='huawei_nbi_umts')
    op.drop_table('UNODEBIP', schema='huawei_nbi_umts')
    op.drop_table('UNODEPARA', schema='huawei_nbi_umts')
    op.drop_table('UNRNC', schema='huawei_nbi_umts')
    op.drop_table('UNRNCRSVPARA', schema='huawei_nbi_umts')
    op.drop_table('UNRNCURA', schema='huawei_nbi_umts')
    op.drop_table('UPCCPCH', schema='huawei_nbi_umts')
    op.drop_table('UPCH', schema='huawei_nbi_umts')
    op.drop_table('UPCPICH', schema='huawei_nbi_umts')
    op.drop_table('UPICH', schema='huawei_nbi_umts')
    op.drop_table('UPSCH', schema='huawei_nbi_umts')
    op.drop_table('URAC', schema='huawei_nbi_umts')
    op.drop_table('URACH', schema='huawei_nbi_umts')
    op.drop_table('USAC', schema='huawei_nbi_umts')
    op.drop_table('USMLC', schema='huawei_nbi_umts')
    op.drop_table('USMLCCELL', schema='huawei_nbi_umts')
