"""Create Huawei 2G NBI starter tables for CM data

Revision ID: b1d3b008f91c
Revises: 1dcef2efb983
Create Date: 2018-04-22 23:13:08.209000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d3b008f91c'
down_revision = '1dcef2efb983'
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('BTS',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ABISBYPASSMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSDESC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FLEXABISMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INNBBULICSHAEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRABBPOOLSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IPPHYTRANSTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISCONFIGEDRING', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAINBMPMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAINPORTNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MPMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SEPERATEMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SERVICEMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRANMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('WORKMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRANDETSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TSASSIGNOPTISW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ADMSTAT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSPAGBLKSRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSPBCCHBLKS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSPRACHBLKS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CSDSP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CSVSP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXTTP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FLEXMAIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GLOCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HYBHIFREQBANDSUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUOTP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MOCNCMCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSHPSP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSLPSVP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REMARK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VIPCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GCELLBASICPARA',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSADJUST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CALLRESTABDIS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELL8PSKPOWERLEVEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLSCENARIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CMEPRIOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIRECTRYEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVERT16QAMDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVERT32QAMDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVERT8PSKDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DNPCEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNOPENTRXPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM1ST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM2ND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM3RD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM4TH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM5TH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM6TH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM7TH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FASTCALLTCHTHRESHOLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FRDLDTX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FRULDTX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GMSKDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GMSKDELAYDYNADJSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HIGHMODPWREN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HRDLDTX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HRULDTX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ICBALLOW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IMMASSCBB', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IMMASSEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IMMTCHLOADTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAYER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LEVELRPT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXTA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MICCSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBAMRTFOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PDCH2SDEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('POWERREDUCE16QAM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('POWERREDUCE32QAM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RTPSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RXMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SDDYN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SVHOCNGSTTHR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SVHODTXDTCTIMER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SVHOHODELAYTIMER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SVHOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TIMESLOTVOLADJALLOW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UMAISSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPPCEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GCELLLCS',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ALTIDECI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ALTITUDE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTAANGLE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INCLUDEANG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INPUTMD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LATIDECI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LATIINT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LONGIDECI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LONGIINT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NSLATI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('WELONGI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GTRX',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ADMSTAT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FREQ', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GTRXGROUPID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISMAINBCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISTMPTRX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('BSCBASIC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ABISVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AIPCSDSRVRDNDLEV', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AMRHOCODECPOLICY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AREACODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCAVN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCGLOBALIDENTITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCPVN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CBPROTOCOLSPEC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CICDMUTEDIFCNT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CICDMUTEPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CICDMUTESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CICDMUTETHRE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CICDMUTETIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CROCALTMTHRD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CSPREHSCSDSECHANSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENPREEMPTABISLVDSADMT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENPREEMPTISCADMT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENPREEMPTTRANSADMT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENQUETRANSADMT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENTCAUSE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENTSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCCHK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GETBTSNETTBLTIMETHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCSUSERHIGHPRILEV', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HIFREQBANDSUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HSCSDCHANGEMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISCCONGALMCLRTH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISCCONGALMTH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MSISDNPREFIX1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MSISDNPREFIX2', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MSISDNPREFIX3', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MSISDNPREFIX4', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MSISDNPREFIX5', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MUTETESTLOGSTYLE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SERVICEMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN10', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN11', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN12', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN13', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN14', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN15', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN16', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN17', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN18', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN19', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN2', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN20', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN3', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN4', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN5', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN6', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN7', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN8', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SINGLEPASSEXCLUDEMSISDN9', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPEECHALMPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPEECHCHANALARMTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPEECHCHANRESUMEALARMTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPEECHCHNALMMUTESTATTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPEECHERRORFORCEHOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPTRANSHARING', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPORTTFOCODECOPTIMIZE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSMSG10ALLOWED', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCCRCALLOWED', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCHBUSYTHRESOPT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UMCROSSDECTECTSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UMVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('SYS',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSCONTACT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSDESC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSLOCATION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSOBJECTID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSSERVICES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('CELLBIND2BTS',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GEXT2GCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCIDX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CMEPRIOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('COMSC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT2GCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT2GCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOPUNISHVALUE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IBCAIIINTERBSCHOINFOSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISEDGESUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISGPRSSUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISNC2SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAYER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADACCTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADHOENEXT2G', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MSRXMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SDPUNTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SDPUNVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TIMEPUNISH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GEXTLTECELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENODEBTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EUTRANTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXTLTECELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXTLTECELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FREQ', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GEXT3GCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLLAYER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVERSITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ECNOTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT3GCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT3GCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FDDECQUALTHRSH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FDDRSCPQUALTHRSH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADACCTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADHOENEXT3G', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MINECNOTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MINRSCPTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSCPTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SCRAMBLE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UTRANCELLTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('G2GNCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ADJHOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BETTERCELLLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BETTERCELLSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BQLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BQMARGIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BQNCELLABSTHRESSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BQSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CHAINNCELLTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRHOLEVRANGE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EDGEADJLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EDGEADJSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EDGEHOHYST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EDOUTHOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GNCELLRANKPRI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HCSLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HCSSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTATICTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HSRPNUSRNCTAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTELEVHOHYST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERCELLHYST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISCHAINNCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LEVLAST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LEVSTAT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADHOPBGTMARGIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MINOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBR2GNCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPRI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPUNEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPUNLEV', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPUNSTPTH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPUNTM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPWRCOMPVALUE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PBGTLAST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PBGTMARGIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PBGTSTAT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRC2GNCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRCHOCTRLSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TALASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TASTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ULBQLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ULBQSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('G3GARFCN',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INPUT3GARFCNEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('G3GNCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ECNOOFF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HODURT3G', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HODURT3GTDD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTAT3G', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTAT3GTDD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBR3GNCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPRI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSCPOFF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRC3GNCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GLTENCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBRLTENCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPRI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPTBLINDHO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPTRAPIDSEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPTRESEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRCLTENCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GTRXCHAN',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ADMSTAT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CHANRSV', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CHNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CHTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GPRSCHPRI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TSPRIORITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GTRXCHANHOP',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CHNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXDSSHOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXDSSMAIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXHOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXMAIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

    op.create_table('GTRXHOP',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('ne_xsitype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('netype', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('neid', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_type', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_remark', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('module_productversion', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOPTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_nbi_gsm'
    )

def downgrade():
    op.drop_table('BTS', schema='huawei_nbi_gsm')
    op.drop_table('GCELL', schema='huawei_nbi_gsm')
    op.drop_table('GCELLBASICPARA', schema='huawei_nbi_gsm')
    op.drop_table('GCELLLCS', schema='huawei_nbi_gsm')
    op.drop_table('GTRX', schema='huawei_nbi_gsm')
    op.drop_table('BSCBASIC', schema='huawei_nbi_gsm')
    op.drop_table('SYS', schema='huawei_nbi_gsm')
    op.drop_table('CELLBIND2BTS', schema='huawei_nbi_gsm')
    op.drop_table('GEXT2GCELL', schema='huawei_nbi_gsm')
    op.drop_table('GEXTLTECELL', schema='huawei_nbi_gsm')
    op.drop_table('GEXT3GCELL', schema='huawei_nbi_gsm')
    op.drop_table('G2GNCELL', schema='huawei_nbi_gsm')
    op.drop_table('G3GARFCN', schema='huawei_nbi_gsm')
    op.drop_table('G3GNCELL', schema='huawei_nbi_gsm')
    op.drop_table('GLTENCELL', schema='huawei_nbi_gsm')
    op.drop_table('GTRXCHAN', schema='huawei_nbi_gsm')
    op.drop_table('GTRXCHANHOP', schema='huawei_nbi_gsm')
    op.drop_table('GTRXHOP', schema='huawei_nbi_gsm')

