"""Add migrations for Huawei WCDMA BSC6900

Revision ID: b2031f71d167
Revises: bcf65a006663
Create Date: 2018-04-11 10:40:15.136000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2031f71d167'
down_revision = 'bcf65a006663'
branch_labels = None
depends_on = None

def upgrade():
    op.create_table('UCELL_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BANDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLKSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CCHCNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCOVERAGETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHETFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CFGRACIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DISPLAYPERFDATADEACELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DLPOWERAVERAGEWINDOWSIZE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DLTPCPATTERN01COUNT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPGID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DSSFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DSSSMALLCOVMAXTXPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ERACHACTFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FLEXUEGROUPNETLAYERID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IPDLFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXTXPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBMSACTFLG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MIMOACTFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NEEDSELFPLANFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NINSYNCIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODESYNSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NOUTSYNCIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('POWERRAISELIMIT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PRIORITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSCRAMBCODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REMARK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPGID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPLITCELLIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPBMC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TIMER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRLFAILURE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TXDIVERSITYIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNDOWNLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINKIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VPLIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('RNCBASIC_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADSHARINGTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXCALLCAPABILITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXTHROUGHPUT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NSAP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REDUNDANCYTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('INTERFREQNCELL_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CLBFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDECN0THRESHHOLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDORLDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDTARGETULCOVERLIMITTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCELLSHUTDOWNFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOCOVPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERFREQADJSQHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERNCELLQUALREQFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER_ANR_WHITELIST_FLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER_BLACKLIST_FLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER_CO_COVERAGE_FLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('READSFNIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UINTERNCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('INTRAFREQNCELL_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLSFORBIDDEN1A', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLSFORBIDDEN1B', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCELLSHUTDOWNFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IMPORTFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBMSNCELLIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER_ANR_WHITELIST_FLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER_BLACKLIST_FLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('READSFNIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UINTRANCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('USMLCEXT3GCELL_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSACTIVATEFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNAALTITUDEMETER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNALATITUDEDEGREE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNALONGITUDEDEGREE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNAOPENING', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNAORIENTATION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLAVERAGEHEIGHT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLENVIRONMENT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHEIGHTSTD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLIDRTTACTIVATEFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLLOCCFGTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCDF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXANTENNARANGE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MTRLGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OTDOAACTIVATEFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RXTXCHANDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TXCHANDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('LTENCELL_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ULTENCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('URA_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('URAID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('SYS_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPORTRNCINPOOL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSDESC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSOBJECTID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('SMLC_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSADDASSDATASENDFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSMEASLONGPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSMEASSHORTPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSMETHODTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ASSDATARSPTIMERLEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLIDRTTMEASPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLIDRTTMETHODTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EMERGLCSSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FORCEDSHOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FSHONEWRLWAITTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRAFREQMEASPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUPCRSPTIMERLEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LCSWORKMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXGPSSATS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPTIONALIESENDSWITCH_LAST_KNOWN_SERVICE_AREA_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPTIONALIESENDSWITCH_R5_POSDATA_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OTDOAMEASPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OTDOAMETHODTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RESULTGEOTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RTTMEASFILTERCOEFF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SATELEVATIONCUTOFFANGLE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD_AGPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD_CELLID_CENTER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD_CELLID_RTT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD_OTDOA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD_UTDOA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_DGPS_CORRECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_ACQ_ASSIST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_ALMANAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_IONOSPHERIC_MODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_NAVGMODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_REALTIME_INTEGRITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_UTC_MODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_REFERENCE_LOCATION_FOR_GPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_REFERENCE_TIME_FOR_GPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_DGPS_CORRECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_ACQ_ASSIST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_ALMANAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_IONOSPHERIC_MODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_NAVGMODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_REALTIME_INTEGRITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_UTC_MODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_REFERENCE_LOCATION_FOR_GPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_REFERENCE_TIME_FOR_GPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UTDOAMEASTIMERLEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('NRNCCELL_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORSAMECELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORUNCELLH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORUNCELLNOH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ALLSERVICELIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('APFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BANDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_CPC_DTX_DRX_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_CPC_HS_SCCH_LESS_OPER_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_DELAY_ACTIVATION_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_2MS_TTI_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_2SF2_AND_2SF4_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_2SF2_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_2SF4_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_HARQ_CHASE_COMBIN_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_HARQ_IR_COMBIN_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_SF4_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_SF8_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_FDPCH_SLOT_FORMAT_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_FDPCH_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_FLEX_MACD_PDU_SIZE_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_HSDSCH_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_HSPAPLUS_DL_64QAM_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_HSPAPLUS_MIMO_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCOVERAGETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CFGRACIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCESUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EFACHSUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FASTHSCCACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HARQPREACAP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HIGHRATERLACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXALLOWEDULTXPOWERIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MIDRATERLACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MOVEUSERPSLIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORHIGHRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORLOWRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORMIDRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OVERLAYMOBILITYFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSCRAMBCODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QQUALMININD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMININD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPLITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPDPCMODECHGFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TXDIVERSITYIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNDOWNLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINKIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('USEOFHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VPLIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('NRNC_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CSVOICEOVERHSPASUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPCSPDF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FUNCTIONSWITCH_AMBR_SUPPORT_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FUNCTIONSWITCH_EXTD_LAC_PAGING_SUPPORT_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FUNCTIONSWITCH_IUR_CARRY_CELL_ANTENNA_POS_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HHORELOCPROCSWITCH_DL_DCCH_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HHORELOCPROCSWITCH_IUR_TRG_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HHOTRIG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBCPPRIVATEINTERFACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBUPPRIVATEINTERFACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURALGOSWITCH_EDCH_SF_LIMIT_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURALGOSWITCH_IUR_SUPP_LTE_EXT_BAND_SW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURCRSTVOICEDPCOVERSUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREDCHSFSUPP_EDCH_2SF2_AND_2SF4_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREDCHSFSUPP_EDCH_2SF2_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREDCHSFSUPP_EDCH_2SF4_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREDCHSFSUPP_EDCH_SF128_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREDCHSFSUPP_EDCH_SF16_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREDCHSFSUPP_EDCH_SF256_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREDCHSFSUPP_EDCH_SF32_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREDCHSFSUPP_EDCH_SF4_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREDCHSFSUPP_EDCH_SF64_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREDCHSFSUPP_EDCH_SF8_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREXISTIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURHSDPASUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURHSUPASUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURIMPVDULCVRSRBODCHIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURLTECELLINFOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURMULTHSPASUPPIND_DC_IUR_HSDPA_RLCC_SUPPORT_R9', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURMULTHSPASUPPIND_IUR_DB_HSDPA_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURMULTHSPASUPPIND_IUR_DC_HSDPA_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURPRIVATEINTERFACESWITCH_PLMNID_INCLUDED', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURPRIVATEINTERFACESWITCH_RL_DELETION_WITH_RELCAUSE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURRLFAILSUSPSHODELTMR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURSMLESSCRSTVOICESUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURSRBOVEREDCHSUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPCSPDF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_COMP_UL_DPDCH_IND_FOR_EDCH_IE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_DSCR_DRNC_RRC_REDIR_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_HSDPA_IE_COMPATIBLE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_HSDPA_PS_BE_QOS_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_IUR_HSDPA_SERV_CELL_CHG_CMP_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_IUR_HSPA_HHO_SUPP_BY_RL_ADD_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_IUR_R99_HHO_SUPP_BY_RL_ADD_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_NRNC_ADD_ONE_RL_SHO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_NRNC_COMPATIBLE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_NRNC_TRANSINFO_COMPATIBLE_1_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_NRNC_TRANSINFO_COMPATIBLE_2_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_NRNC_TRANS_BEAR_REEST_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_R99_PS_BE_QOS_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_RNC_NODE_REDUNDANCY_COMPATIBLE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_UL_INTEG_ALGO_FOR_IUR_CU_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSBEPROCTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCPROTCLVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT10', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT11', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT12', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT13', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT14', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT15', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT16', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT17', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT18', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT19', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT2', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT20', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT21', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT22', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT23', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT24', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT25', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT26', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT27', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT28', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT29', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT3', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT30', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT31', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT32', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT4', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT5', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT6', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT7', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT8', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1_BIT9', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA2', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SERVICEIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHOTRIG_CS_SHO_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHOTRIG_HSPA_SHO_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHOTRIG_NON_HSPA_SHO_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPCBITS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRNSWITHCSFBINDSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('STATEINDTMR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPIURCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TNLBEARERTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('WAMRSUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('BCH_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('CNOPERATOR_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPERATORNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPERATORTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('LAC_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PLMNVALTAGMAX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PLMNVALTAGMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('NODEB_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AUTOHOMINGFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLKSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DSSFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBFLEXFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBAUTOREDUNDANCYFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBPROTCLVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBTRACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSCMNGMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SATELLITEIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHARINGTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIGNALCREATETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TNLBEARERTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRANSDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('NODEBALGOPARA_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ADPETADJFUNCSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HSUPACECONSUMESELECTION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBBWCGSTTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBBWNONCGSTTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBREMAINBWTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBMINNERSWITCH_CELL_BASIC_CCH_DL_CE_CAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBMINNERSWITCH_CELL_BASIC_CCH_UL_CE_CAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBALGOENHSWITCH_ENH_DYNCAPSFC_ON_NCP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBALGOENHSWITCH_NODEB_CRYSTAL_VOICE_DEEPCOVER_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBALGOENHSWITCH_NODEB_IMPVD_UL_COVER_FOR_SRBODCH_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBALGOENHSWITCH_NODEB_SEAMLESS_CRYSTAL_VOICE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBHSDPAMAXUSERNUM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBHSUPAMAXUSERNUM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_IUB_LDR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_IUB_OLC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_LCG_CREDIT_CLB_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_LCG_CREDIT_LDR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_NODEB_CREDIT_CLB_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_NODEB_CREDIT_LDR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT10', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT11', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT12', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT13', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT14', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT15', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT16', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT2', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT3', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT4', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT5', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT6', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT7', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT8', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA1_RSVDBIT9', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA2', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVDPARA3', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVSWITCH0', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPLINKACTIVESETEXP_CCPIC_PHASE2_COORDINATING_RL_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPLINKACTIVESETEXP_IMPRV_ULCOV_SRBOD_COORDINATING_RL_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPLINKACTIVESETEXP_SMLESSCRSTVOICE_COORDINATING_RL_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('NodeBFunction_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('APPLICATIONREF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERFACEID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LMTVERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NERMVERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBFUNCTIONNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OBJID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PRODUCTVERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('PICH_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PICHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PICHMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('STTDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

    op.create_table('PSCH_BSC6900UMTS',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DATETIME', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSCHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_wcdma'
    )

def downgrade():
    op.drop_table('UCELL_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('RNCBASIC_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('INTERFREQNCELL_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('INTRAFREQNCELL_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('USMLCEXT3GCELL_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('LTENCELL_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('URA_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('SYS_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('SMLC_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('NRNCCELL_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('NRNC_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('BCH_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('CNOPERATOR_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('LAC_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('NODEB_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('NODEBALGOPARA_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('NodeBFunction_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('PICH_BSC6900UMTS', schema='huawei_gexport_wcdma')
    op.drop_table('PSCH_BSC6900UMTS', schema='huawei_gexport_wcdma')
