"""Create Huawei Gexport GSM tables

Revision ID: bcf65a006663
Revises: 41c8d1841d45
Create Date: 2018-03-28 06:56:21.767000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf65a006663'
down_revision = '41c8d1841d45'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('GCELL_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ADMSTAT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCCHNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSPAGBLKSRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSPBCCHBLKS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSPRACHBLKS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CGI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CSDSP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CSVSP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CnOpIndex', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DISPERFDATADEACELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXTTP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FLEXMAIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GLOCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HYBHIFREQBANDSUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUOTP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MOCNCMCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NEWCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSHPSP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSLPSVP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REMARK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SiteIndex', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VIPCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('BSCBASIC_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ABISVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AIPCSDSRVRDNDLEV', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AMRHOCODECPOLICY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AREACODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ATERTRANSMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCAVN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCGLOBALIDENTITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCPVN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CBPROTOCOLSPEC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CICDMUTEDIFCNT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CICDMUTEPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CICDMUTESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CICDMUTETHRE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CICDMUTETIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CROCALTMTHRD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CSPREHSCSDSECHANSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENPREEMPTABISLVDSADMT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENPREEMPTISCADMT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENPREEMPTTRANSADMT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENQUETRANSADMT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENTCAUSE_CALL_SETUP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENTCAUSE_IMSI_ATTACH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENTCAUSE_IMSI_DETACH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENTCAUSE_NORMAL_LOCATION_UPDATE', sa.CHAR(length=250), autoincrement=False,
                  nullable=True),
        sa.Column('ENTCAUSE_OTHERS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENTCAUSE_PAGING_RESPONSE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENTCAUSE_PERIOD_LOCATION_UPDATE', sa.CHAR(length=250), autoincrement=False,
                  nullable=True),
        sa.Column('ENTCAUSE_SMS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENTSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCCHK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GETBTSNETTBLTIMETHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCSUSERHIGHPRILEV', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HIFREQBANDSUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HSCSDCHANGEMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISCCONGALMCLRTH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISCCONGALMTH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISSUPPORTTCPOOL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MUTETESTLOGSTYLE_CIC_MUTETEST_LOG_REC', sa.CHAR(length=250), autoincrement=False,
                  nullable=True),
        sa.Column('MUTETESTLOGSTYLE_IP_MUTETEST_LOG_REC', sa.CHAR(length=250), autoincrement=False,
                  nullable=True),
        sa.Column('MUTETESTLOGSTYLE_IP_PACKET_CHECK_LOG_REC', sa.CHAR(length=250), autoincrement=False,
                  nullable=True),
        sa.Column('MUTETESTLOGSTYLE_LEV1_MUTETEST_LOG_REC', sa.CHAR(length=250), autoincrement=False,
                  nullable=True),
        sa.Column('MUTETESTLOGSTYLE_LEV2_MUTETEST_LOG_REC', sa.CHAR(length=250), autoincrement=False,
                  nullable=True),
        sa.Column('MUTETESTLOGSTYLE_UP_ABNORMAL_CHECK_LOG_REC', sa.CHAR(length=250), autoincrement=False,
                  nullable=True),
        sa.Column('NOISEALMSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RMTTCATERTRANSMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SERVICEMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPEECHALMPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPEECHCHANALARMTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPEECHCHANRESUMEALARMTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPEECHCHNALMMUTESTATTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPEECHERRORFORCEHOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPTRANSHARING', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPORTTFOCODECOPTIMIZE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSMSG10ALLOWED', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCCRCALLOWED', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCHBUSYTHRESOPT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UMCROSSDECTECTSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UMVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('WBTONBHO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('SYS_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSDESC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSOBJECTID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('CELLBIND2BTS_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('GEXT2GCELL_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT2GCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCIDX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCN2GCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CGI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('COMSC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT2GCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOPUNISHVALUE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IBCAIIINTERBSCHOINFOSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISEDGESUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISGPRSSUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISNC2SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAYER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADACCTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADHOENEXT2G', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MSRXMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PRIOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SDPUNTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SDPUNVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TIMEPUNISH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('GEXTLTECELL_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXTLTECELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCNLTECELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENODEBTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EUTRANTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXTLTECELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FREQ', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('GEXT3GCELL_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT3GCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCN3GCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLLAYER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVERSITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ECNOTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT3GCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FDDECQUALTHRSH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FDDRSCPQUALTHRSH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADACCTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADHOENEXT3G', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MINECNOTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MINRSCPTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSCPTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SCRAMBLE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UTRANCELLTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('GEXTSMLC_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCIDX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LCSSHAPETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TAREQWAITVALIDMRTIMER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('BTS_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ABISBYPASSMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ABISMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSDESC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CPUNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CTRLSN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CTRLSRN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CURE1INPORTNUM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FLEXABISMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INNBBULICSHAEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRABBPOOLSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISCONFIGEDRING', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAINBMPMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAINPORTNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MPMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NEWNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMLLOGICNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SEPERATEMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SERVICEMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRANUPGRADEFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRANDETSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TSASSIGNOPTISW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPOMLINPORTNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPOMLINTSNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPOMLOUTBSCE1PORTNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPOMLOUTBSCSLOTNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPOMLOUTBSCSUBRACKNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPOMLOUTBSCTSNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('WORKMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('GCELLBASICPARA_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BFEDGEMTX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSADJUST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CALLRESTABDIS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELL8PSKPOWERLEVEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLSCENARIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('COMPSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIRECTRYEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVERT16QAMDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVERT32QAMDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVERT8PSKDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DLCOMBFILTERSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DNPCEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNOPENTRXPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRY_A5/0', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRY_A5/1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRY_A5/2', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRY_A5/3', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRY_A5/4', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRY_A5/5', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRY_A5/6', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRY_A5/7', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM1ST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM2ND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM3RD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM4TH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM5TH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM6TH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENCRYPTIONALGORITHM7TH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FASTCALLTCHTHRESHOLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FRDLDTX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FRULDTX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GMSKDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GMSKDELAYDYNADJSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HIGHMODPWREN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HRDLDTX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HRULDTX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ICBALLOW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IMMASSCBB', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IMMASSEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IMMTCHLOADTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAYER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LEVELRPT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXTA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MICCSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBAMRTFOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PDCH2SDEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('POWERREDUCE16QAM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('POWERREDUCE32QAM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PRIOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RTPSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RXMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SDDYN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIGDECODEENSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SVHOCNGSTTHR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SVHODTXDTCTIMER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SVHOHODELAYTIMER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SVHOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TIMESLOTVOLADJALLOW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ULROTSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UMAISSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPPCEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('GTRX_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ABISMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ADMSTAT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTPASSNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BTSID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BUFZONETRXSHAREFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CABINETNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DISPERFDATADEATRX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FREQ', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GTRXGROUPID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISMAINBCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISTMPTRX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NEWTRXNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TEI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRANSTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXABILITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXPN1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRXSHAREFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPOUTBSCE1PORTNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPOUTBSCSLOTNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPOUTBSCSUBRACKNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPOUTBSCTSNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPRSLLOGICNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPRSLPORTNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPRSLTSNO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )

    op.create_table('GCELLLCS_BSC6900GSM',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TECHNOLOGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VENDOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ALTIDECI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ALTITUDE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTAANGLE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INCLUDEANG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INPUTMD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LATIDECI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LATIINT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LONGIDECI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LONGIINT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NSLATI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('WELONGI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_gexport_gsm'
        )


def downgrade():
    op.drop_table('GCELL_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('BSCBASIC_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('SYS_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('CELLBIND2BTS_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('GEXT2GCELL_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('GEXTLTECELL_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('GEXT3GCELL_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('GEXTSMLC_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('BTS_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('GCELLBASICPARA_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('GTRX_BSC6900GSM', schema='huawei_gexport_gsm')
    op.drop_table('GCELLLCS_BSC6900GSM', schema='huawei_gexport_gsm')
