"""Create import tables for huawei rnp cm data

Revision ID: da1630c92802
Revises: aad19c87fcee
Create Date: 2018-12-14 15:10:59.382714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da1630c92802'
down_revision = 'aad19c87fcee'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('UCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BANDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNDOWNLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSCRAMBCODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPGID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('URAIDS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXTXPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PCPICHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHETFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REMARK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TEMPLATENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('G2GNCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BIDIRECTION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRCCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBRCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRC2GNCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBR2GNCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRCHOCTRLSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERCELLHYST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MINOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PBGTMARGIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BQMARGIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISCHAINNCELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTELEVHOHYST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRHOLEVRANGE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CHAINNCELLTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EDGEADJSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EDGEADJLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LEVSTAT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LEVLAST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PBGTSTAT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PBGTLAST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BETTERCELLSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BETTERCELLLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTATICTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HCSSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HCSLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BQSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BQLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TASTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TALASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ULBQSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ULBQLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IBCADYNCMEASURENCELLALLOWED', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IBCARXLEVOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADHOPBGTMARGIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPRI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EDOUTHOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPUNEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPUNSTPTH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPUNTM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPUNLEV', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ADJHOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EDGEHOHYST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GNCELLRANKPRI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPWRCOMPVALUE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BQNCELLABSTHRESSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HSRPNUSRNCTAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('COMPCOCELLSTARTHYST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('COMPCOCELLSTOPHYST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('COMPCOCELLSTATTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('COMPCOCELLLASTTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLSCETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('G3GNCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BIDIRECTION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRCCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBRCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRC3GNCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBR3GNCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSCPOFF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ECNOOFF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTAT3GTDD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HODURT3GTDD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTAT3G', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HODURT3G', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPRI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('GEXT2GCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT2GCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT2GCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('COMSC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAYER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CMEPRIOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SDPUNVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SDPUNTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MSRXMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TIMEPUNISH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOPUNISHVALUE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADHOENEXT2G', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADACCTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISNC2SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISGPRSSUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ISEDGESUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCIDX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IBCAIIINTERBSCHOINFOSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('GEXT3GCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT3GCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXT3GCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLLAYER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SCRAMBLE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVERSITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UTRANCELLTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYNCCASE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ECNOTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MINECNOTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FDDECQUALTHRSH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FDDRSCPQUALTHRSH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TDDRSCPQUALTHRSH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSCPTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MINRSCPTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADHOENEXT3G', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADACCTHRES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('GEXTLTECELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXTLTECELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EXTLTECELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ENODEBTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FREQ', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EUTRANTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('GLTENCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BIDIRECTION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRCCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBRCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRCLTENCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBRLTENCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPTRESEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPTBLINDHO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPTRAPIDSEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLPRI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EUTRANNCELLHIGHTHLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EUTRANNCELLLOWTHLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EUTRANNCELLRXLEVMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('GSMCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBSCINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LDPRDRPRTSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CFGRACIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCCHARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BANDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RATCELLTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('USEOFHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HCSPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPRIMFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPPSHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMVOICEWEAKRXLEVTHLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH1ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH2ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH3ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH4ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH5ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH6ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('GSMNCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BIDIRECTION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TEMPOFFSET1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDECN0THRESHHOLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRVCCSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERRATADJSQHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NIRATOVERLAP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('U2GNCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('INTERFREQNCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BIDIRECTION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TEMPOFFSET1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TEMPOFFSET2', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOCOVPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOQUALITYCONDITION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDECN0THRESHHOLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDORLDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERNCELLQUALREQFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QQUALMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERFREQADJSQHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CLBFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CLBPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UINTERNCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDTARGETULCOVERLIMITTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCELLSHUTDOWNFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('INTRAFREQNCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BIDIRECTION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLSFORBIDDEN1A', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLSFORBIDDEN1B', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TEMPOFFSET1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TEMPOFFSET2', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBMSNCELLIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UINTRANCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCELLSHUTDOWNFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('LTECELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EUTRANCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLPHYID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTEBAND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTEARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPPSHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLACKFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('U2LRIMCNOPERATORRTINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SLAVEBANDINDICATOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('LTENCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BIDIRECTION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ULTENCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('NODEB',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TNLBEARERTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRANSDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SATELLITEIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBPROTCLVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSCMNGMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBTRACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PEERRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PEERNODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PREFERRNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHARINGTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DSSFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AUTOHOMINGFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIGNALCREATETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBFLEXFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBAUTOREDUNDANCYFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REMARK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLKSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTSTATUS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('NRNCCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSCRAMBCODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BANDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINKIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNDOWNLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SLAVENRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TXDIVERSITYIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CFGRACIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MIDRATERLACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HIGHRATERLACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORLOWRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORMIDRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORHIGHRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORUNCELLNOH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORUNCELLH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORSAMECELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QQUALMININD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QQUALMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMININD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMINEXTSUP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DELTAQRXLEVMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXALLOWEDULTXPOWERIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXALLOWEDULTXPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('USEOFHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HCSPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPDPCMODECHGFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('STTDSUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CP1SUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CLOSEDLOOPTIMEADJUSTMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPCHDIVMODFOROTHER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FDPCHDIVMODFOROTHER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPCHDIVMODFORMIMO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FDPCHDIVMODFORMIMO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DIVMODFORDCHSDPA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OVERLAYMOBILITYFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HARQPREACAP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EFACHSUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('APFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VPLIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FASTHSCCACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCESUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MOVEUSERPSLIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPLITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCOVERAGETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ALLSERVICELIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSSERVICELIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CSSERVICELIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

    op.create_table('USMLCEXT3GCELL',
        sa.Column('FILENAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NE_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BSCName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOGICRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLLOCCFGTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GCDF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MTRLGY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNALATITUDEDEGREE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNALONGITUDEDEGREE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNAALTITUDEMETER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXANTENNARANGE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNAORIENTATION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNAOPENING', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLAVERAGEHEIGHT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHEIGHTSTD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLENVIRONMENT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TXCHANDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RXTXCHANDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLIDRTTACTIVATEFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OTDOAACTIVATEFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSACTIVATEFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCENTERLATITUDE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCENTERLONGITUDE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCENTERALTITUDE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UNCERTSEMIMAJOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UNCERTSEMIMINOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ORIENTOFMAJORAXIS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UNCERTALTITUDE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNALATITUDEDEGREESEC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNALONGITUDEDEGREESEC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCENTERLATITUDESEC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCENTERLONGITUDESEC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ANTENNAALTITUDEMETERIMP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXANTENNARANGEIMP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLAVERAGEHEIGHTIMP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHEIGHTSTDIMP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCENTERALTITUDEIMP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UNCERTSEMIMAJORIMP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UNCERTSEMIMINORIMP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UNCERTALTITUDEIMP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_rnp'
    )

def downgrade():
    op.drop_table('UCELL', schema='huawei_rnp')
    op.drop_table('G2GNCELL', schema='huawei_rnp')
    op.drop_table('G3GNCELL', schema='huawei_rnp')
    op.drop_table('GEXT2GCELL', schema='huawei_rnp')
    op.drop_table('GEXT3GCELL', schema='huawei_rnp')
    op.drop_table('GEXTLTECELL', schema='huawei_rnp')
    op.drop_table('GLTENCELL', schema='huawei_rnp')
    op.drop_table('GSMCELL', schema='huawei_rnp')
    op.drop_table('GSMNCELL', schema='huawei_rnp')
    op.drop_table('INTERFREQNCELL', schema='huawei_rnp')
    op.drop_table('INTRAFREQNCELL', schema='huawei_rnp')
    op.drop_table('LTECELL', schema='huawei_rnp')
    op.drop_table('LTENCELL', schema='huawei_rnp')
    op.drop_table('NODEB', schema='huawei_rnp')
    op.drop_table('NRNCCELL', schema='huawei_rnp')
    op.drop_table('USMLCEXT3GCELL', schema='huawei_rnp')

