"""Create Huawei MML 3G starter MOs

Revision ID: f9286015dea6
Revises: b1d3b008f91c
Create Date: 2018-04-24 00:14:14.063000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9286015dea6'
down_revision = 'b1d3b008f91c'
branch_labels = None
depends_on = None


def upgrade():
    op.create_table('UCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UBCH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('SYS',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSDESC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSOBJECTID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSCONTACT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSLOCATION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SYSSERVICES', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPORTRNCINPOOL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('U2GNCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TEMPOFFSET1', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDECN0THRESHHOLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRVCCSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERRATADJSQHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NIRATOVERLAP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('U2GNCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UINTRAFREQNCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLSFORBIDDEN1A', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLSFORBIDDEN1B', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBMSNCELLIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UINTRANCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCELLSHUTDOWNFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER_BLACKLIST_FLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER_ANR_WHITELIST_FLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UINTERFREQNCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDLEQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NPRIOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDHOQUALITYCONDITION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIOOFFSET', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB11IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIB12IND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TPENALTYHCSRESELECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOCOVPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDECN0THRESHHOLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBDRPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDORLDRFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERNCELLQUALREQFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTERFREQADJSQHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CLBFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UINTERNCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET1SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CONNQOFFSET2SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DRDTARGETULCOVERLIMITTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DYNCELLSHUTDOWNFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER_CO_COVERAGE_FLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER_BLACKLIST_FLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCELLCAPCONTAINER_ANR_WHITELIST_FLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('ULAC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PLMNVALTAGMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PLMNVALTAGMAX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('ULTECELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLPHYID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTEBAND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTEARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPPSHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EUTRANCELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLACKFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('U2LRIMCNOPERATORRTINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SLAVEBANDINDICATOR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UNODEB',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SRN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SSN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IPTRANSAPARTIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TNLBEARERTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TRANSDELAY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SATELLITEIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBPROTCLVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHARINGTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSCMNGMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBTRACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DSSFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AUTOHOMINGFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SIGNALCREATETYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBFLEXFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBAUTOREDUNDANCYFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UNRNC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUREXISTIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHOTRIG_CS_SHO_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHOTRIG_HSPA_SHO_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SHOTRIG_NON_HSPA_SHO_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HHOTRIG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SERVICEIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCPROTCLVER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('STATEINDTMR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPIURCCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HHORELOCPROCSWITCH_DL_DCCH_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HHORELOCPROCSWITCH_IUR_TRG_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURHSDPASUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURHSUPASUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CSVOICEOVERHSPASUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSBEPROCTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBCPPRIVATEINTERFACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBUPPRIVATEINTERFACESWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_RNC_NODE_REDUNDANCY_COMPATIBLE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_HSDPA_IE_COMPATIBLE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PROCESSSWITCH_NRNC_COMPATIBLE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURPRIVATEINTERFACESWITCH_PLMNID_INCLUDED', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IURPRIVATEINTERFACESWITCH_RL_DELETION_WITH_RELCAUSE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('WAMRSUPPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TNLBEARERTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NI', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPCBITS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SPC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPCSPDF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('DPCSPDF', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UCNOPERATOR',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPERATORNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPERATORTYPEULAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('USAC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UEXT3GCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NRNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLHOSTTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINKIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNUPLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UARFCNDOWNLINK', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CFGRACIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QQUALMININD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QRXLEVMININD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXALLOWEDULTXPOWERIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSCRAMBCODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BANDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TXDIVERSITYIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MIDRATERLACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HIGHRATERLACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORLOWRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORMIDRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OAMGUARDVALFORHIGHRATE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORUNCELLNOH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORUNCELLH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ACTTIMEDEFOFFVALFORSAMECELL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('USEOFHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPDPCMODECHGFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_DELAY_ACTIVATION_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_HSDSCH_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_FDPCH_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_2MS_TTI_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_2SF2_AND_2SF4_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_2SF2_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_2SF4_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_SF4_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_SF8_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_HARQ_IR_COMBIN_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_EDCH_HARQ_CHASE_COMBIN_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_CPC_DTX_DRX_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_CPC_HS_SCCH_LESS_OPER_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_HSPAPLUS_MIMO_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_FLEX_MACD_PDU_SIZE_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_FDPCH_SLOT_FORMAT_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLCAPCONTAINERFDD_HSPAPLUS_DL_64QAM_SUPPORT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OVERLAYMOBILITYFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HARQPREACAP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EFACHSUPIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('APFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('VPLIMITIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FASTHSCCACTTIMEDEFOFFVAL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HCSPRIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('QHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UEXT2GCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMCELLNAME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MNC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPGRPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CFGRACIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BCCHARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BANDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RATCELLTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('USEOFHCS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NCMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPRIMFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SUPPPSHOFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CIO', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NBSCINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LDPRDRPRTSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('GSMVOICEWEAKRXLEVTHLD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH1ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH2ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH3ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH4ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH5ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('TCH6ARFCN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UPICH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PICHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PICHMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('STTDIND', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UPSCH',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PHYCHID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PSCHPOWER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('USMLC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD_CELLID_CENTER', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD_CELLID_RTT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD_OTDOA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD_AGPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SMLCMETHOD_UTDOA', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSMETHODTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSMEASLONGPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSMEASSHORTPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('AGPSADDASSDATASENDFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_REFERENCE_TIME_FOR_GPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_REFERENCE_LOCATION_FOR_GPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_DGPS_CORRECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_NAVGMODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_IONOSPHERIC_MODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_UTC_MODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_ALMANAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_ACQ_ASSIST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEASSAGPSASSDATASWITCH_GPS_REALTIME_INTEGRITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_REFERENCE_TIME_FOR_GPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_REFERENCE_LOCATION_FOR_GPS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_DGPS_CORRECT', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_NAVGMODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_IONOSPHERIC_MODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_UTC_MODEL', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_ALMANAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_ACQ_ASSIST', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UEBASAGPSASSDATASWITCH_GPS_REALTIME_INTEGRITY', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MAXGPSSATS', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OTDOAMETHODTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLIDRTTMETHODTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('EMERGLCSSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPTIONALIESENDSWITCH_R5_POSDATA_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OPTIONALIESENDSWITCH_LAST_KNOWN_SERVICE_AREA_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FORCEDSHOSWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LCSWORKMODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUPCRSPTIMERLEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RESULTGEOTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UTDOAMEASTIMERLEN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('SATELEVATIONCUTOFFANGLE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('INTRAFREQMEASPERIOD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('FSHONEWRLWAITTIME', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('ULTENCELL',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CELLID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LTECELLINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BLINDFLAG', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ULTENCELLSRC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('UNODEBALGOPARA',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_IUB_LDR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_NODEB_CREDIT_LDR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_LCG_CREDIT_LDR', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_IUB_OLC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_NODEB_CREDIT_CLB_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBLDCALGOSWITCH_LCG_CREDIT_CLB_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBHSDPAMAXUSERNUM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBHSUPAMAXUSERNUM', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('HSUPACECONSUMESELECTION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBBWCGSTTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBBWNONCGSTTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IUBREMAINBWTHD', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('IDTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBALGOENHSWITCH_ENH_DYNCAPSFC_ON_NCP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBALGOENHSWITCH_NODEB_SEAMLESS_CRYSTAL_VOICE_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBALGOENHSWITCH_NODEB_CRYSTAL_VOICE_DEEPCOVER_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NODEBALGOENHSWITCH_NODEB_IMPVD_UL_COVER_FOR_SRBODCH_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPLINKACTIVESETEXP_CCPIC_PHASE2_COORDINATING_RL_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPLINKACTIVESETEXP_IMPRV_ULCOV_SRBOD_COORDINATING_RL_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('UPLINKACTIVESETEXP_SMLESSCRSTVOICE_COORDINATING_RL_SWITCH', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RSVSWITCH0', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('ADPETADJFUNCSW', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('URAC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RAC', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('CNOPINDEX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PLMNVALTAGMIN', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('PLMNVALTAGMAX', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

    op.create_table('URNCBASIC',
        sa.Column('FileName', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('varDateTime', sa.DateTime, autoincrement=False, nullable=True),
        sa.Column('BSCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('BAM_VERSION', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('OMU_IP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('MBSC MODE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('RNCID', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('NSAP', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('LOADSHARINGTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        sa.Column('REDUNDANCYTYPE', sa.CHAR(length=250), autoincrement=False, nullable=True),
        schema='huawei_mml_umts'
    )

def downgrade():
    op.drop_table('UCELL', schema='huawei_mml_umts')
    op.drop_table('UBCH', schema='huawei_mml_umts')
    op.drop_table('SYS', schema='huawei_mml_umts')
    op.drop_table('U2GNCELL', schema='huawei_mml_umts')
    op.drop_table('UINTRAFREQNCELL', schema='huawei_mml_umts')
    op.drop_table('UINTERFREQNCELL', schema='huawei_mml_umts')
    op.drop_table('ULAC', schema='huawei_mml_umts')
    op.drop_table('ULTECELL', schema='huawei_mml_umts')
    op.drop_table('UNODEB', schema='huawei_mml_umts')
    op.drop_table('UNRNC', schema='huawei_mml_umts')
    op.drop_table('UCNOPERATOR', schema='huawei_mml_umts')
    op.drop_table('USAC', schema='huawei_mml_umts')
    op.drop_table('UEXT3GCELL', schema='huawei_mml_umts')
    op.drop_table('UEXT2GCELL', schema='huawei_mml_umts')
    op.drop_table('UPICH', schema='huawei_mml_umts')
    op.drop_table('UPSCH', schema='huawei_mml_umts')
    op.drop_table('USMLC', schema='huawei_mml_umts')
    op.drop_table('ULTENCELL', schema='huawei_mml_umts')
    op.drop_table('UNODEBALGOPARA', schema='huawei_mml_umts')
    op.drop_table('URAC', schema='huawei_mml_umts')
    op.drop_table('URNCBASIC', schema='huawei_mml_umts')
